Repository AdmiralDS/react-ui, pull requests merged in 2022-06, with the labels that each got.

#133 fix(OverflowMenu): fix DropdownContainer position
  src/components/OverflowMenu/Button.tsx
  src/components/OverflowMenu/OverflowMenu.stories.tsx
  src/components/OverflowMenu/__snapshots__/OverflowMenu.test.tsx.snap
  src/components/OverflowMenu/index.tsx
Labels: bug

#138 feat(Modal): add opportunity to hide CloseIcon
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/index.tsx
Labels: feature

#142 fix(Modal): remove overlay blur
  src/components/Modal/index.tsx
Labels: bug

#150 35 numberinput refactor
  admiral-ds-react-ui-1.1.0.tgz
  src/components/input/NumberInput/AutoSizeInput.tsx
  src/components/input/NumberInput/NumberInput.stories.tsx
  src/components/input/NumberInput/index.tsx
  src/components/input/NumberInput/utils.ts
  src/components/input/SliderInput/index.tsx
  src/components/input/SliderRange/SliderRange.stories.tsx
  src/components/input/SliderRange/index.tsx
Labels: feature

#151 fix(Select): fix bug with placeholder color
  admiral-ds-react-ui-1.1.0.tgz
  src/components/input/Select/index.tsx
Labels: bug

#157 feat(Select): add styles for readOnly state
  src/components/input/Select/styled.ts
Labels: feature

#160 feat(MenuButton, TextButtonMenu): use DropMenu
  src/components/DropMenu/index.tsx
  src/components/MenuButton/MenuButton.stories.tsx
  src/components/MenuButton/MenuButton.test.tsx
  src/components/MenuButton/__snapshots__/MenuButton.test.tsx.snap
  src/components/MenuButton/index.tsx
  src/components/TextButtonMenu/TextButtonMenu.stories.tsx
  src/components/TextButtonMenu/index.tsx
  src/index.ts
Labels: enhancement

#166 fix(MenuButton): fix tests
  src/components/MenuButton/MenuButton.test.tsx
  src/components/MenuButton/index.tsx
Labels: bug

#169 feat(Select): add styles for multiple select in readOnly state
  src/components/input/Select/MultipleSelectChips.tsx
  src/components/input/Select/index.tsx
Labels: feature

#175 feat(Table): add opportunity to disable row checkbox
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/MenuButton/__snapshots__/MenuButton.test.tsx.snap
  src/components/MultiButton/__snapshots__/MultiButton.test.tsx.snap
  src/components/Table/Table.stories.tsx
  src/components/Table/index.tsx
Labels: feature

#184 feat(Breadcrumbs): remove ReactDOM.render method, refactor component
  src/components/Breadcrumbs/BreadCrumb.tsx
  src/components/Breadcrumbs/index.tsx
  src/components/Breadcrumbs/style.ts
  src/components/Breadcrumbs/utils.tsx
Labels: enhancement

#185 feat(AvatarGroup): replace old DropDown with new DropMenu
  src/components/Avatar/index.tsx
  src/components/AvatarGroup/AvatarGroup.stories.tsx
  src/components/AvatarGroup/Menu.tsx
  src/components/AvatarGroup/index.tsx
  src/components/DropMenu/DropMenu.stories.tsx
  src/components/DropMenu/index.tsx
  src/components/MenuButton/index.tsx
  src/components/OverflowMenu/index.tsx
  src/components/TextButtonMenu/index.tsx
Labels: enhancement

#192 fix(Breadcrumbs): fix bug with dimension
  src/components/Breadcrumbs/BreadCrumb.tsx
  src/components/Breadcrumbs/index.tsx
Labels: bug

#193 fix(NumberInput): fix bug with copied value and precision 0
  src/components/input/NumberInput/NumberInput.stories.tsx
  src/components/input/NumberInput/utils.ts
Labels: bug

#194 feat(MultiButton): replace Dropdown with new DropMenu
  src/components/DropMenu/DropMenu.stories.tsx
  src/components/DropMenu/index.tsx
  src/components/MenuButton/MenuButton.test.tsx
  src/components/MultiButton/MultiButton.stories.tsx
  src/components/MultiButton/MultiButton.test.tsx
  src/components/MultiButton/__snapshots__/MultiButton.test.tsx.snap
  src/components/MultiButton/index.tsx
  src/components/TextButton/index.tsx
Labels: enhancement

#196 feat(SliderInput): add opportunity to customize labels for slider marks
  src/components/Slider/Slider.stories.tsx
  src/components/Slider/TickMarks.tsx
  src/components/Slider/index.tsx
  src/components/input/SliderInput/SliderInput.stories.tsx
  src/components/input/SliderInput/index.tsx
Labels: feature
