Repository AdmiralDS/react-ui, pull requests merged in 2022-11, with the labels that each got.

#461 feat(Pill): add new component Pill
  src/components/Pill/Pill.stories.tsx
  src/components/Pill/index.tsx
  src/components/TagMenu/TagMenu.stories.tsx
  src/index.ts
Labels: feature

#462 feat(SliderInput): add opportunity to use controlled mode
  src/components/Slider/index.tsx
  src/components/input/SliderInput/SliderInput.stories.tsx
  src/components/input/SliderInput/index.tsx
Labels: feature, refactor

#460 Возможность передать кастомную обертку для строки
  src/components/Table/index.tsx
Labels: enhancement

#464 fix(Modal): fix bug with overflow on left side of ModalContent
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/index.tsx
Labels: bug

#474 305 sliderrange input blur
  src/components/Range/Range.stories.tsx
  src/components/Range/index.tsx
  src/components/Range/style.ts
  src/components/Range/utils.ts
  src/components/RangeRefactor/Range.stories.tsx
  src/components/RangeRefactor/index.tsx
  src/components/RangeRefactor/style.ts
  src/components/RangeRefactor/utils.ts
  src/components/Slider/index.tsx
  src/components/input/SliderInput/index.tsx
  src/components/input/SliderRange/SliderRange.stories.tsx
  src/components/input/SliderRange/index.tsx
Labels: feature

#476 feat(FileItem): show file size in Kb if file is less than 1Mb
  src/components/input/FileInput/FileItem.tsx
  src/components/input/FileInput/utils.ts
  src/components/locale.stories.tsx
  src/components/themes/common/locales.ts
Labels: feature

#478 fix(TimeInput): fix problem with 20-24 hours
  src/components/input/TimeInput/defaultTimeInputHandle.ts
Labels: bug

#483 feat(Table): add opportunity to use empty rows group
  src/components/Table/Row/GroupRow.tsx
  src/components/Table/Row/RowWrapper.tsx
  src/components/Table/index.tsx
  src/components/Table/style.ts
Labels: feature

#484 feat(TagMenu, MultiButton): enable customize DropMenu options
  src/components/MenuButton/index.tsx
  src/components/MultiButton/MultiButton.stories.tsx
  src/components/MultiButton/__snapshots__/MultiButton.test.tsx.snap
  src/components/MultiButton/index.tsx
  src/components/Tag/index.tsx
  src/components/TagMenu/TagMenu.stories.tsx
  src/components/TagMenu/index.tsx
Labels: feature

#490 fix(ContentSwitcher): fix story with icons only
  src/components/ContentSwitcher/ContentSwitcher.stories.tsx
Labels: bug

#492 feat(IconPlacement): add new component
  src/components/AvatarGroup/AvatarGroup.stories.tsx
  src/components/DropDownMenu/DropDownMenu.stories.tsx
  src/components/DropMenu/DropMenu.stories.tsx
  src/components/DropdownContainer/DropDownContainer.stories.tsx
  src/components/GroupActionsPane/GroupActionsPane.stories.tsx
  src/components/Hint/Hint.stories.tsx
  src/components/IconPlacement/IconPlacement.stories.tsx
  src/components/IconPlacement/index.tsx
  src/components/Menu/Menu.stories.tsx
  src/components/MenuButton/MenuButton.stories.tsx
  src/components/Modal/Modal.stories.tsx
  src/components/OverflowMenu/OverflowMenu.stories.tsx
  src/components/RadioButton/RadioButton.stories.tsx
  src/components/TextButtonMenu/TextButtonMenu.stories.tsx
  src/components/Toggle/Toggle.stories.tsx
  src/components/form/FieldSet/FieldSet.stories.tsx
  src/components/input/NumberInput/NumberInput.stories.tsx
  src/components/input/SliderInput/SliderInput.stories.tsx
  src/index.ts
Labels: feature

#496 feat(PhoneNumberInput): change Chevron icon and its margin
  src/components/input/PhoneNumberInput/index.tsx
Labels: feature

#497 466 table rows zebra
  src/components/Table/Row/RowWrapper.tsx
  src/components/Table/Table.stories.tsx
  src/components/Table/index.tsx
  src/components/Table/mixins.ts
  src/components/Table/style.ts
Labels: feature

#500 refactor(Components): use IconPlacement
  src/components/Breadcrumbs/index.tsx
  src/components/Calendar/components/Button.tsx
  src/components/Calendar/components/Panel.tsx
  src/components/Calendar/interfaces.ts
  src/components/Calendar/styled/PanelButton.ts
  src/components/Hint/HintContainer.tsx
  src/components/Hint/style.ts
  src/components/IconPlacement/IconPlacement.stories.tsx
  src/components/IconPlacement/index.tsx
  src/components/Modal/index.tsx
  src/components/Notification/__snapshots__/Notification.test.tsx.snap
  src/components/Notification/index.tsx
  src/components/OverflowMenu/Button.tsx
  src/components/OverflowMenu/__snapshots__/OverflowMenu.test.tsx.snap
  src/components/OverflowMenu/index.tsx
  src/components/TabMenu/__snapshots__/TabMenu.test.tsx.snap
  src/components/TabMenu/constants.ts
  src/components/TabMenu/style.ts
  src/components/Table/Row/GroupRow.tsx
  src/components/Table/Row/RerularRow.tsx
  src/components/Table/RowAction.tsx
  src/components/Table/style.ts
  src/components/Tree/TreeNode.tsx
  src/components/input/FileInput/FileInput.stories.tsx
  src/components/input/FileInput/FileItem.tsx
Labels: feature, refactor

#504 452 table bug zoom overflowmenurender
  src/components/Table/OverflowMenu.tsx
  src/components/Table/Row/GroupRow.tsx
  src/components/Table/Row/RegularRow.tsx
  src/components/Table/Row/RowWrapper.tsx
  src/components/Table/index.tsx
  src/components/Table/style.ts
Labels: bug, feature

#508 feat(themes): add 6px and 10px border radius
  src/components/Button/Button.stories.tsx
  src/components/Calendar/Calendar.stories.tsx
  src/components/Checkbox/Checkbox.stories.tsx
  src/components/CheckboxCompositeGroup/CheckboxCompositeGroup.stories.tsx
  src/components/DropDownMenu/DropDownMenu.stories.tsx
  src/components/DropMenu/DropMenu.stories.tsx
  src/components/DropdownContainer/DropDownContainer.stories.tsx
  src/components/Field/Field.stories.tsx
  src/components/Hint/Hint.stories.tsx
  src/components/IconButton/IconButton.stories.tsx
  src/components/Link/Link.stories.tsx
  src/components/Menu/Menu.stories.tsx
  src/components/MenuButton/MenuButton.stories.tsx
  src/components/Modal/Modal.stories.tsx
  src/components/MultiButton/MultiButton.stories.tsx
  src/components/Notification/Notification.stories.tsx
  src/components/OverflowMenu/OverflowMenu.stories.tsx
  src/components/PaginationOne/PaginationOne.stories.tsx
  src/components/Pill/Pill.stories.tsx
  src/components/TabMenu/TabMenu.stories.tsx
  src/components/Tag/Tag.stories.tsx
  src/components/TagMenu/TagMenu.stories.tsx
  src/components/Tags/Tags.stories.tsx
  src/components/TextButton/TextButton.stories.tsx
  src/components/TextButtonMenu/TextButtonMenu.stories.tsx
  src/components/Toast/Toast.stories.tsx
  src/components/Tooltip/Tooltip.stories.tsx
  src/components/form/CheckboxField/CheckboxField.stories.tsx
  src/components/form/DateField/DateField.stories.tsx
  src/components/form/DateTimeField/DateTimeField.stories.tsx
  src/components/form/EditModeField/EditModeField.stories.tsx
  src/components/form/FieldSet/FieldSet.stories.tsx
  src/components/form/InputExField/InputExField.stories.tsx
  src/components/form/InputField/InputField.stories.tsx
  src/components/form/NumberInputField/NumberInputField.stories.tsx
  src/components/form/PhoneInputField/PhoneInputField.stories.tsx
  src/components/form/SelectField/SelectField.stories.tsx
  src/components/form/SliderInputField/SliderInputField.stories.tsx
  src/components/form/SliderRangeField/SliderRangeField.stories.tsx
  src/components/form/SuggestField/SuggestField.stories.tsx
  src/components/form/TextField/TextField.stories.tsx
  src/components/form/TimeField/TimeField.stories.tsx
  src/components/input/DateInput/DateInput.stories.tsx
  src/components/input/EditMode/EditMode.stories.tsx
  src/components/input/FileInput/FileInput.stories.tsx
  src/components/input/FileUploader/FileUploader.stories.tsx
  src/components/input/InputEx/InputEx.stories.tsx
  src/components/input/NumberInput/NumberInput.stories.tsx
  src/components/input/PhoneNumberInput/PhoneNumberInput.stories.tsx
  src/components/input/Select/Stories/SearchSelect.stories.tsx
  src/components/input/Select/Stories/Select.stories.tsx
  src/components/input/SliderInput/SliderInput.stories.tsx
  src/components/input/SliderRange/SliderRange.stories.tsx
  src/components/input/SuggestInput/SuggestInput.stories.tsx
  src/components/input/TextArea/TextArea.stories.tsx
  src/components/input/TextInput/TextInput.stories.tsx
  src/components/input/TimeInput/TimeInput.stories.tsx
  src/components/themes/borderRadius.ts
  src/components/themes/common/index.ts
Labels: feature

#509 feat(FileItem): add file type and icon handlers
  src/components/input/FileInput/FileItem.tsx
  src/components/input/FileInput/utils.ts
Labels: feature

#513 refactor(Chips): use CloseIconPlacementButton
  src/components/Chips/Chips.stories.tsx
  src/components/Chips/__snapshots__/Chips.test.tsx.snap
  src/components/Chips/index.tsx
  src/components/Chips/style.ts
  src/components/IconPlacement/IconPlacement.stories.tsx
  src/components/input/Select/Select.test.tsx
Labels: refactor

#515 feat(Tooltip): if renderContent result is empty, tooltip will not dis…
  src/components/Tooltip/index.tsx
  src/components/TooltipHOC/index.tsx
Labels: feature

#516 486 feature modal change scroll position
  src/components/Modal/index.tsx
Labels: feature

#518 fix IconPlacement shrink
  src/components/IconPlacement/index.tsx
  src/components/Notification/__snapshots__/Notification.test.tsx.snap
  src/components/OverflowMenu/__snapshots__/OverflowMenu.test.tsx.snap
  src/components/TabMenu/__snapshots__/TabMenu.test.tsx.snap
Labels: bug

#521 fix(Table): fix column minWidth which can be achieved by column resize
  src/components/Table/index.tsx
Labels: bug
