Repository AdmiralDS/react-ui, pull requests merged in 2022-07, with the labels that each got.

#211 173 table data attributes
  src/components/Range/index.tsx
  src/components/Range/style.ts
  src/components/Slider/index.tsx
  src/components/Slider/style.ts
  src/components/Table/OverflowMenu.tsx
  src/components/Table/RowWidthResizer.tsx
  src/components/Table/data.tsx
  src/components/Table/index.tsx
  src/components/Table/mixins.ts
  src/components/Table/style.ts
  src/components/input/NumberInput/AutoSizeInput.tsx
  src/components/input/NumberInput/index.tsx
Labels: bug

#215 feat(Calendar): calendar has fixed height
  src/components/Accordion/Accordion.stories.tsx
  src/components/Calendar/components/Month.tsx
  src/components/Modal/Modal.stories.tsx
  src/components/Stepper/Stepper.stories.tsx
  src/index.ts
Labels: feature

#217 216 bugs storybook
  src/components/Button/Button.stories.tsx
  src/components/Hint/Hint.stories.tsx
  src/components/Table/data.tsx
Labels: bug

#220 fix(OverflowMenu): fix focus style and fix OverflowMenu dimension in …
  src/components/Breadcrumbs/Menu.tsx
  src/components/Breadcrumbs/index.tsx
  src/components/OverflowMenu/Button.tsx
  src/components/OverflowMenu/__snapshots__/OverflowMenu.test.tsx.snap
  src/components/OverflowMenu/index.tsx
Labels: bug

#223 222 dropdownprovider useclickoutside
  src/components/Dropdown/index.tsx
  src/components/DropdownContainer/index.tsx
  src/components/DropdownProvider.tsx
  src/components/Hint/HintContainer.tsx
  src/components/common/hooks/useClickOutside.ts
Labels: bug

#221 feat(TabMenu): remove ReactDOM.render method, refactor component
  src/components/MultiButton/index.tsx
  src/components/OverflowMenu/Button.tsx
  src/components/TabMenu/TabMenu.stories.tsx
  src/components/TabMenu/TabMenu.test.tsx
  src/components/TabMenu/__snapshots__/TabMenu.test.tsx.snap
  src/components/TabMenu/constants.ts
  src/components/TabMenu/index.tsx
  src/components/TabMenu/measureTab.tsx
  src/components/TabMenu/style.ts
Labels: enhancement

#242 179 refactor icons select input
  src/components/Table/RowAction.tsx
  src/components/Table/style.ts
  src/components/form/DateField/DateField.stories.tsx
  src/components/form/EditModeField/EditModeField.stories.tsx
  src/components/form/InputField/InputField.stories.tsx
  src/components/form/NumberInputField/NumberInputField.stories.tsx
  src/components/form/PhoneInputField/PhoneInputField.stories.tsx
  src/components/form/SelectField/SelectField.stories.tsx
  src/components/form/SliderInputField/SliderInputField.stories.tsx
  src/components/form/SuggestField/SuggestField.stories.tsx
  src/components/form/TextField/TextField.stories.tsx
  src/components/form/TimeField/TimeField.stories.tsx
  src/components/input/DateInput/index.tsx
  src/components/input/EditMode/EditMode.stories.tsx
  src/components/input/NumberInput/NumberInput.stories.tsx
  src/components/input/NumberInput/index.tsx
  src/components/input/PhoneNumberInput/PhoneNumberInput.stories.tsx
  src/components/input/PhoneNumberInput/index.tsx
  src/components/input/Select/Select.stories.tsx
  src/components/input/Select/index.tsx
  src/components/input/Select/styled.ts
  src/components/input/SliderInput/SliderInput.stories.tsx
  src/components/input/SliderInput/index.tsx
  src/components/input/SliderRange/SliderRange.stories.tsx
  src/components/input/SliderRange/index.tsx
  src/components/input/SuggestInput/index.tsx
  src/components/input/TextArea/TextArea.stories.tsx
  src/components/input/TextArea/index.tsx
  src/components/input/TextInput/TextInput.stories.tsx
  src/components/input/TextInput/index.tsx
  src/components/input/TimeInput/TimeInput.stories.tsx
  src/components/input/TimeInput/index.tsx
Labels: feature

#243 202 hint contolled state
  src/components/Hint/Hint.stories.tsx
  src/components/Hint/Hint.test.tsx
  src/components/Hint/HintContainer.tsx
  src/components/Hint/index.tsx
  src/components/Hint/reducer.ts
  src/components/RadioButton/RadioButton.stories.tsx
  src/components/form/CheckboxField/CheckboxField.stories.tsx
  src/components/input/Select/MultipleSelectChips.tsx
Labels: feature

#245 feat(PaginationOne): replace Dropdown with new DropMenu
  src/components/AvatarGroup/index.tsx
  src/components/PaginationOne/Menu.tsx
  src/components/PaginationOne/PaginationOne.stories.tsx
  src/components/PaginationOne/index.tsx
Labels: feature

#247 feat(Toggle): set new color in active disabled state
  src/components/Toggle/index.tsx
Labels: feature

#248 feat(Chips): add badges
  src/components/Badge/index.tsx
  src/components/Chips/Chips.stories.tsx
  src/components/Chips/index.tsx
  src/components/Chips/style.ts
Labels: feature
