Repository AdmiralDS/react-ui, pull requests merged in 2022-10, with the labels that each got.

#409 fix(Components with menu): fix double scroll and styles
  src/components/Breadcrumbs/Menu.tsx
  src/components/Breadcrumbs/index.tsx
  src/components/DropMenu/index.tsx
  src/components/DropdownContainer/index.tsx
  src/components/GroupActionsPane/ColumnsButton.tsx
  src/components/GroupActionsPane/index.tsx
  src/components/Menu/Menu.stories.tsx
  src/components/Menu/index.tsx
  src/components/PaginationOne/index.tsx
  src/components/TabMenu/index.tsx
  src/components/Table/filter/Filter.tsx
  src/components/input/DateInput/index.tsx
  src/components/input/InputEx/SuffixSelect.tsx
  src/components/input/InputEx/index.tsx
  src/components/input/PhoneNumberInput/index.tsx
  src/components/input/SuggestInput/SuggestInput.stories.tsx
  src/components/input/SuggestInput/index.tsx
  src/components/input/TimeInput/index.tsx
Labels: bug

#415 382 refactor tooltip
  src/components/Avatar/index.tsx
  src/components/Breadcrumbs/BreadCrumb.tsx
  src/components/Breadcrumbs/Menu.tsx
  src/components/Calendar/components/Button.tsx
  src/components/Calendar/components/Panel.tsx
  src/components/Calendar/interfaces.ts
  src/components/Calendar/styled/PanelDate.ts
  src/components/Chips/index.tsx
  src/components/DropMenu/DropMenu.stories.tsx
  src/components/Menu/Menu.stories.tsx
  src/components/Modal/index.tsx
  src/components/PaginationOne/PaginationOne.stories.tsx
  src/components/PaginationOne/index.tsx
  src/components/PaginationTwo/index.tsx
  src/components/ProgressStepper/ProgressStepper.stories.tsx
  src/components/ProgressStepper/ProgressStepper.test.tsx
  src/components/ProgressStepper/index.tsx
  src/components/Stepper/StepContent.tsx
  src/components/T/T.stories.tsx
  src/components/Table/Table.stories.tsx
  src/components/Table/TitleText.tsx
  src/components/Table/data.tsx
  src/components/Table/index.tsx
  src/components/Tag/index.tsx
  src/components/Tooltip/Tooltip.stories.tsx
  src/components/Tooltip/Tooltip.test.tsx
  src/components/Tooltip/index.tsx
  src/components/Tooltip/utils.ts
  src/components/TooltipHOC/index.tsx
  src/components/input/EditMode/index.tsx
  src/components/input/FileUploader/FileInfo.tsx
  src/components/input/Select/DisplayValue.tsx
  src/components/input/Select/index.tsx
  src/components/input/SuggestInput/SuggestInput.stories.tsx
  src/components/input/SuggestInput/index.tsx
  src/components/input/TextInput/index.tsx
  src/icons/Icons.stories.tsx
Labels: refactor

#416 feat(FileInput): add new component FileInput instead of FileUploader
  src/components/Dropdown/index.tsx
  src/components/Toggle/__snapshots__/Toggle.test.tsx.snap
  src/components/Toggle/index.tsx
  src/components/input/FileInput/FileInput.stories.tsx
  src/components/input/FileInput/FileItem.tsx
  src/components/input/FileInput/index.tsx
  src/components/input/FileInput/style.ts
  src/components/input/FileInput/utils.ts
  src/components/input/FileUploader/FileUploader.stories.tsx
  src/components/input/FileUploader/index.tsx
  src/components/input/index.ts
Labels: refactor

#421 feat(FileInput): add props for synchronizing file lists and for extra text
  src/components/Field/index.tsx
  src/components/input/FileInput/FileInput.stories.tsx
  src/components/input/FileInput/index.tsx
Labels: bug, feature

#423 Fix story name
  src/components/input/FileUploader/FileUploader.stories.tsx
Labels: bug

#425 fix: fix Range export
  src/index.ts
Labels: bug

#429 fix(Storybook): pass loading and disabled in DropMenu stories examples
  src/components/DropMenu/DropMenu.stories.tsx
Labels: bug

#430 343 table update checkbox column width
  src/components/Table/style.ts
Labels: bug

#431 306 slider bug animation
  src/components/Slider/Slider.stories.tsx
  src/components/Slider/index.tsx
  src/components/Slider/style.ts
  src/components/Slider/utils.ts
  src/components/input/SliderInput/index.tsx
Labels: bug

#432 feat(MenuItemWithCheckbox): add checkbox menu item component
  src/components/DropMenu/index.tsx
  src/components/Menu/Menu.stories.tsx
  src/components/Menu/MenuItemWithCheckbox.tsx
  src/components/Menu/index.tsx
  src/index.ts
Labels: feature

#436 fix(Tree, Menu with CheckboxGroup): fix indeterminate parent state
  src/components/Menu/Menu.stories.tsx
  src/components/Menu/MenuItemWithCheckbox.tsx
  src/components/Tree/TreeNode.tsx
  src/components/Tree/index.tsx
Labels: bug

#438 fix(TagMenu): pass id to Menu's selected prop
  src/components/TagMenu/index.tsx
Labels: bug

#439 Fix - Calendar - fix focus and icon click behavior
  src/components/input/DateInput/index.tsx
  src/components/input/InputEx/SuffixSelect.tsx
  src/components/input/TimeInput/index.tsx
Labels: bug

#454 fix(DropMenu): fix passing props and control state
  src/components/DropMenu/DropMenu.stories.tsx
  src/components/DropMenu/index.tsx
  src/components/Menu/Menu.stories.tsx
  src/components/Menu/MenuItemWithCheckbox.tsx
  src/components/Menu/index.tsx
Labels: bug

#455 434 range bug animation
  src/components/RangeRefactor/Range.stories.tsx
  src/components/RangeRefactor/index.tsx
  src/components/RangeRefactor/style.ts
  src/components/RangeRefactor/utils.ts
  src/components/Slider/index.tsx
Labels: bug

#457 435 table tooltip title
  src/components/Table/TitleText.tsx
  src/components/Table/index.tsx
Labels: bug

#458 456 fix fix props in components with dropmenu
  src/components/AvatarGroup/index.tsx
  src/components/DropMenu/index.tsx
  src/components/MenuButton/MenuButton.stories.tsx
  src/components/MenuButton/index.tsx
  src/components/MultiButton/MultiButton.stories.tsx
  src/components/MultiButton/index.tsx
  src/components/OverflowMenu/OverflowMenu.stories.tsx
  src/components/OverflowMenu/index.tsx
  src/components/PaginationOne/Menu.tsx
  src/components/PaginationOne/index.tsx
  src/components/TabMenu/TabMenu.stories.tsx
  src/components/Table/OverflowMenu.tsx
  src/components/Table/Table.stories.tsx
  src/components/Table/data.tsx
  src/components/Table/index.tsx
  src/components/TagMenu/TagMenu.stories.tsx
  src/components/TagMenu/index.tsx
  src/components/TextButtonMenu/TextButtonMenu.stories.tsx
  src/components/TextButtonMenu/index.tsx
Labels: bug
