Repository AdmiralDS/react-ui, pull requests merged in 2022-09, with the labels that each got.

#353 fix(Components with DropMenu): set classname to wrapper
  src/components/AvatarGroup/AvatarGroup.stories.tsx
  src/components/AvatarGroup/index.tsx
  src/components/MenuButton/MenuButton.stories.tsx
  src/components/MultiButton/MultiButton.stories.tsx
  src/components/MultiButton/__snapshots__/MultiButton.test.tsx.snap
  src/components/MultiButton/index.tsx
  src/components/OverflowMenu/OverflowMenu.stories.tsx
  src/components/OverflowMenu/index.tsx
  src/components/PaginationOne/Menu.tsx
  src/components/TagMenu/TagMenu.stories.tsx
  src/components/TagMenu/index.tsx
  src/components/TextButtonMenu/TextButtonMenu.stories.tsx
  src/components/TextButtonMenu/index.tsx
Labels: bug

#354 fix(SliderInputField, SliderRangeField): fix problem with field overflow
  src/components/form/SliderInputField/index.tsx
  src/components/form/SliderRangeField/index.tsx
Labels: bug

#355 feat(Inputs): add tooltip for long option text
  src/components/Avatar/index.tsx
  src/components/Breadcrumbs/BreadCrumb.tsx
  src/components/Breadcrumbs/Menu.tsx
  src/components/Calendar/components/Panel.tsx
  src/components/Chips/index.tsx
  src/components/DropMenu/DropMenu.stories.tsx
  src/components/Menu/Menu.stories.tsx
  src/components/Stepper/StepContent.tsx
  src/components/Stepper/Stepper.stories.tsx
  src/components/T/T.stories.tsx
  src/components/Table/TitleText.tsx
  src/components/Table/data.tsx
  src/components/Tag/index.tsx
  src/components/Tooltip/index.tsx
  src/components/common/utils/checkOverflow.ts
  src/components/input/EditMode/index.tsx
  src/components/input/FileUploader/FileInfo.tsx
  src/components/input/Select/DisplayValue.tsx
  src/components/input/Select/index.tsx
  src/components/input/TextInput/index.tsx
Labels: feature

#360 313 bug timeinput
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/components/CheckboxCompositeGroup/__snapshots__/CheckboxCompositeGroup.test.tsx.snap
  src/components/CheckboxGroup/__snapshots__/CheckBoxGroup.test.tsx.snap
  src/components/MenuButton/__snapshots__/MenuButton.test.tsx.snap
  src/components/MultiButton/__snapshots__/MultiButton.test.tsx.snap
  src/components/RadioButton/__snapshots__/RadioButton.test.tsx.snap
  src/components/SelectTree/__snapshots__/SelectTree.test.tsx.snap
  src/components/form/CheckboxField/__snapshots__/CheckboxField.test.tsx.snap
  src/components/input/TimeInput/defaultTimeInputHandle.ts
  src/icons/IconComponents-category.ts
  src/icons/IconComponents-documents.ts
Labels: bug

#370 feat(TimeInput): add uncontrolled mode
  src/components/input/TimeInput/index.tsx
Labels: feature

#371 366 table forwardref rowaction
  src/components/Table/RowAction.tsx
  src/components/Table/Table.stories.tsx
  src/components/Table/data.tsx
  src/components/Table/index.tsx
Labels: bug

#377 fix(Table): fix horizontal scroll when emptyMessage displays
  src/components/Table/index.tsx
  src/components/Table/style.ts
Labels: bug

#380 fix(Breadcrumbs): fix bug with hidden menu breadcrumbs and router link
  src/components/Breadcrumbs/Menu.tsx
Labels: bug

#381 fix(Table): disable header checkbox when rowList is empty
  src/components/Table/OverflowMenu.tsx
  src/components/Table/Row/RowWrapper.tsx
  src/components/Table/VirtualBody.tsx
  src/components/Table/index.tsx
  src/components/Table/style.ts
Labels: bug

#386 369 hint position scroll
  src/components/Hint/utils.ts
Labels: bug

#389 336 refactor inputs table replace deprecated dropdown
  src/components/Menu/index.tsx
  src/components/Table/filter/Filter.tsx
  src/components/input/DateInput/index.tsx
  src/components/input/Select/index.tsx
  src/components/input/SuggestInput/MessagePanel.tsx
  src/components/input/SuggestInput/SuggestInput.stories.tsx
  src/components/input/SuggestInput/SuggestInput.test.tsx
  src/components/input/SuggestInput/SuggestPanel.tsx
  src/components/input/SuggestInput/index.tsx
  src/components/input/TextInput/TextInput.stories.tsx
  src/components/input/TextInput/index.tsx
  src/components/input/TimeInput/Slot.tsx
  src/components/input/TimeInput/index.tsx
  src/components/input/TimeInput/utils.ts
Labels: feature

#391 390 sliderinput positive numbers
  src/components/Table/Table.stories.tsx
  src/components/Table/index.tsx
  src/components/input/NumberInput/AutoSizeInput.tsx
  src/components/input/NumberInput/index.tsx
  src/components/input/NumberInput/utils.ts
Labels: bug, feature

#398 fix(Table): fix action and overflowMenu position on horizontal scroll
  src/components/Table/OverflowMenu.tsx
  src/components/Table/index.tsx
  src/components/Table/style.ts
Labels: bug

#400 392 replace observerect with resizeobserver
  src/components/AvatarGroup/index.tsx
  src/components/TabMenu/TabMenu.test.tsx
  src/components/TabMenu/index.tsx
  src/components/Table/index.tsx
  src/components/input/NumberInput/AutoSizeInput.tsx
Labels: refactor

#402 359 breadcrumbs incorrect menu calc items change
  src/components/Breadcrumbs/Menu.tsx
  src/components/Breadcrumbs/index.tsx
Labels: bug

#404 fix(Tree): leave line selected after toggle expand and checkbox
  src/components/Tree/TreeNode.tsx
  src/components/Tree/index.tsx
Labels: bug

#405 feat(SuggestInput): add storybook examples with no matches and filtering
  src/components/input/SuggestInput/MessagePanel.tsx
  src/components/input/SuggestInput/SuggestInput.stories.tsx
Labels: feature

#407 feat(Toast): add return id to addToast method, add removeById method
  src/components/Toast/Toast.stories.tsx
  src/components/Toast/ToastProvider.tsx
  src/components/Toast/index.tsx
  src/components/Toast/useToast.tsx
Labels: feature
