Repository AdmiralDS/react-ui, pull requests merged in 2023-06, with the labels that each got.

#957 fix(Table): fix bug with column width and vertical scroll
  packages/react-ui/src/components/Table/index.tsx
  packages/react-ui/src/components/Table/style.ts
Labels: bug

#967 fix(Hint, Tooltip): fix bug with z-index
  packages/react-ui/src/components/Drawer/index.tsx
  packages/react-ui/src/components/Hint/style.ts
  packages/react-ui/src/components/Tooltip/style.ts
  packages/react-ui/src/components/themes/common/zIndex.ts
Labels: bug

#968 860 groupactionspane api tooltip
  packages/react-ui/src/components/GroupActionsPane/ColumnsButton.tsx
  packages/react-ui/src/components/GroupActionsPane/Stories/Templates/PaneSimple.tsx
  packages/react-ui/src/components/GroupActionsPane/index.tsx
Labels: feature

#973 fix(PhoneNumberInput): fix Chevron position
  packages/react-ui/src/components/input/PhoneNumberInput/index.tsx
Labels: bug

#978 feat(Button): add iconStart/iconEnd props
  packages/react-ui/src/components/Button/Stories/Templates/ButtonPlayground.tsx
  packages/react-ui/src/components/Button/Stories/Templates/ButtonStyles.tsx
  packages/react-ui/src/components/Button/Stories/Templates/ButtonWithIcon.tsx
  packages/react-ui/src/components/Button/dimensionMixin.ts
  packages/react-ui/src/components/Button/index.tsx
  packages/react-ui/src/components/Button/types.ts
  packages/react-ui/src/components/TextButton/index.tsx
Labels: enhancement

#979 feat(Avatar, AvatarGroup): update appearance names
  packages/react-ui/src/components/Avatar/Avatar_SVG.tsx
  packages/react-ui/src/components/Avatar/Stories/Avatar.stories.tsx
  packages/react-ui/src/components/Avatar/Stories/Templates/SingleAvatar.tsx
  packages/react-ui/src/components/Avatar/index.tsx
  packages/react-ui/src/components/AvatarGroup/Stories/AvatarGroup.stories.tsx
  packages/react-ui/src/components/AvatarGroup/Stories/Templates/AvatarGroupPlayground.tsx
  packages/react-ui/src/components/AvatarGroup/Stories/Templates/AvatarGroupWidth.tsx
  packages/react-ui/src/components/AvatarGroup/index.tsx
Labels: feature

#982 Fix using icon in button
  packages/react-ui/src/components/Hint/Stories/Templates/HintAnchorCss.tsx
  packages/react-ui/src/components/Hint/Stories/Templates/HintBase.tsx
  packages/react-ui/src/components/Hint/Stories/Templates/HintClassName.tsx
  packages/react-ui/src/components/Hint/Stories/Templates/HintClick.tsx
  packages/react-ui/src/components/Hint/Stories/Templates/HintTarget.tsx
  packages/react-ui/src/components/Hint/Stories/Templates/HintTextButton.tsx
  packages/react-ui/src/components/input/EditMode/index.tsx
Labels: feature

#983 847 table story upload data during scroll
  packages/react-ui/src/components/Table/Stories/Table.stories.tsx
  packages/react-ui/src/components/Table/Stories/Templates/TableLoadOnScroll.tsx
  packages/react-ui/src/components/Table/Stories/Templates/index.tsx
  packages/react-ui/src/components/Table/index.tsx
Labels: documentation

#977 Обеспечить возможность отображения иконки(вертикальное многоточие) дл…
  packages/react-ui/src/components/Table/OverflowMenu.tsx
  packages/react-ui/src/components/Table/Row/RowWrapper.tsx
  packages/react-ui/src/components/Table/Stories/Table.stories.tsx
  packages/react-ui/src/components/Table/Stories/Templates/TableOverflowMenu.tsx
  packages/react-ui/src/components/Table/index.tsx
  packages/react-ui/src/components/Table/mixins.ts
  packages/react-ui/src/components/Table/style.ts
Labels: feature
