Repository AdmiralDS/react-ui, pull requests merged in 2023-09, with the labels that each got.

#1097 fix(Button): исправлен баг с изменением ширины кнопки при переходе от…
  src/components/Button/index.tsx
  src/components/MenuButton/__snapshots__/MenuButton.test.tsx.snap
Labels: bug

#1103 fix Tag docs in storybook
  src/components/Tag/stories/Tag.stories.tsx
  src/components/Tag/stories/TagCustomColors.template.tsx
Labels: documentation

#1114 1080 table sort column type
  src/components/Table/stories/Table.stories.tsx
  src/components/Table/stories/TableSort.template.tsx
  src/components/Table/types.ts
Labels: feature

#1116 1092 storybook сдалать цвет текста в примерах компонентов переключаемым в зависимости от темы
  src/components/Badge/stories/BadgePlayground.template.tsx
  src/components/Badge/stories/BadgeVariants.template.tsx
  src/components/Flex/stories/FlexPlayground.template.tsx
  src/components/Pill/stories/PillMenu.template.tsx
  src/components/Pill/stories/PillNested.template.tsx
  src/components/Pill/stories/PillSimple.template.tsx
  src/components/Pill/stories/PillWithTooltip.template.tsx
  src/components/TooltipHOC/stories/TooltipHocClass.template.tsx
  src/components/TooltipHOC/stories/TooltipHocFC.template.tsx
  src/components/input/FileUploader/stories/FileUploaderCustom.template.tsx
  src/components/input/InputEx/stories/InputExCustom.template.tsx
  src/components/input/Select/stories/styled.ts
Labels: documentation

#1119 1109 table data attrs
  src/components/Table/Row/GroupRow.tsx
  src/components/Table/Row/RegularRow.tsx
  src/components/Table/Row/RowWrapper.tsx
  src/components/Table/index.tsx
  src/components/Table/stories/Table.stories.tsx
Labels: enhancement
