Repository AdmiralDS/react-ui, pull requests merged in 2023-03, with the labels that each got.

#715 feat(Table): add filterMenuAlignSelf and filterMenuCssMixin props for…
  src/components/Table/Table.stories.tsx
  src/components/Table/filter/Filter.tsx
  src/components/Table/index.tsx
Labels: feature

#718 Fix props description in Toast provider
  src/components/Toast/ToastProvider.tsx
Labels: documentation

#719 fix(NotificationItem): add missing types to export
  src/index.ts
Labels: bug

#729 fix(DropMenu): fix using isVisible prop
  src/components/DropMenu/index.tsx
  src/components/MenuButton/MenuButton.stories.tsx
  src/components/input/DateInput/DateInput.stories.tsx
  src/components/input/DateInput/index.tsx
Labels: bug, feature

#785 feat(Components with Drop): add dropContainerClassName and dropContainerStyle props
  src/components/AvatarGroup/AvatarGroup.stories.tsx
  src/components/AvatarGroup/index.tsx
  src/components/Breadcrumbs/Breadcrumbs.stories.tsx
  src/components/Breadcrumbs/Menu.tsx
  src/components/Breadcrumbs/index.tsx
  src/components/DropMenu/DropMenu.stories.tsx
  src/components/DropMenu/index.tsx
  src/components/DropdownContainer/DropDownContainer.stories.tsx
  src/components/DropdownContainer/index.tsx
  src/components/GroupActionsPane/ColumnsButton.tsx
  src/components/GroupActionsPane/GroupActionsPane.stories.tsx
  src/components/GroupActionsPane/SettingsButton.tsx
  src/components/GroupActionsPane/index.tsx
  src/components/MenuButton/MenuButton.stories.tsx
  src/components/MenuButton/index.tsx
  src/components/MultiButton/MultiButton.stories.tsx
  src/components/MultiButton/index.tsx
  src/components/OverflowMenu/OverflowMenu.stories.tsx
  src/components/OverflowMenu/index.tsx
  src/components/PaginationOne/Menu.tsx
  src/components/PaginationOne/PaginationOne.stories.tsx
  src/components/PaginationOne/index.tsx
  src/components/Pill/Pill.stories.tsx
  src/components/TabMenu/TabMenu.stories.tsx
  src/components/TabMenu/index.tsx
  src/components/Table/Table.stories.tsx
  src/components/Table/filter/Filter.tsx
  src/components/Table/index.tsx
  src/components/TagMenu/TagMenu.stories.tsx
  src/components/TagMenu/index.tsx
  src/components/TextButtonMenu/TextButtonMenu.stories.tsx
  src/components/TextButtonMenu/index.tsx
  src/components/form/DateField/DateField.stories.tsx
  src/components/form/DateTimeField/DateTimeField.stories.tsx
  src/components/form/InputExField/InputExField.stories.tsx
  src/components/form/PhoneInputField/PhoneInputField.stories.tsx
  src/components/form/SelectField/SelectField.stories.tsx
  src/components/form/SuggestField/SuggestField.stories.tsx
  src/components/form/TimeField/TimeField.stories.tsx
  src/components/input/DateInput/DateInput.stories.tsx
  src/components/input/DateInput/index.tsx
  src/components/input/InputEx/InputEx.stories.tsx
  src/components/input/InputEx/SuffixSelect.tsx
  src/components/input/InputEx/index.tsx
  src/components/input/PhoneNumberInput/PhoneNumberInput.stories.tsx
  src/components/input/PhoneNumberInput/index.tsx
  src/components/input/Select/Stories/SearchSelect.stories.tsx
  src/components/input/Select/Stories/Select.stories.tsx
  src/components/input/Select/index.tsx
  src/components/input/SuggestInput/SuggestInput.stories.tsx
  src/components/input/SuggestInput/index.tsx
  src/components/input/TimeInput/TimeInput.stories.tsx
  src/components/input/TimeInput/index.tsx
Labels: feature

#788 766 fix docs
  src/components/PaginationSimple/PaginationSimple.stories.tsx
  src/components/RadioButton/RadioButton.stories.tsx
  src/components/Stepper/Stepper.stories.tsx
  src/components/Table/Table.stories.tsx
Labels: documentation

#784 fix(DropMenu, OverflowMenu): fix default DropdownContainer position
  src/components/Breadcrumbs/Menu.tsx
Labels: bug

#792 docs: fix stories arguments types
  src/components/DropMenu/DropMenu.stories.tsx
  src/components/TagMenu/TagMenu.stories.tsx
Labels: documentation

#793 fix(SliderRange): fix controls type in storybook
  src/components/form/SliderRangeField/SliderRangeField.stories.tsx
  src/components/input/SliderRange/SliderRange.stories.tsx
Labels: documentation
