Repository AdmiralDS/react-ui, pull requests merged in 2023-05, with the labels that each got.

#888 fix(InputEx): fix hover styles
  packages/react-ui/src/components/form/DateField/DateField.stories.tsx
  packages/react-ui/src/components/form/EditModeField/EditModeField.stories.tsx
  packages/react-ui/src/components/form/InputExField/InputExField.stories.tsx
  packages/react-ui/src/components/form/InputField/InputField.stories.tsx
  packages/react-ui/src/components/form/SuggestField/SuggestField.stories.tsx
  packages/react-ui/src/components/form/TimeField/TimeField.stories.tsx
  packages/react-ui/src/components/input/DateInput/DateInput.stories.tsx
  packages/react-ui/src/components/input/EditMode/EditMode.stories.tsx
  packages/react-ui/src/components/input/InputEx/InputEx.stories.tsx
  packages/react-ui/src/components/input/InputEx/SuffixSelect.tsx
  packages/react-ui/src/components/input/InputEx/index.tsx
  packages/react-ui/src/components/input/PhoneNumberInput/PhoneNumberInput.stories.tsx
  packages/react-ui/src/components/input/TextInput/TextInput.stories.tsx
  packages/react-ui/src/components/input/TextInput/index.tsx
  packages/react-ui/src/components/input/TimeInput/TimeInput.stories.tsx
Labels: bug

#890 feat(Tag,Tags): add proper kind names
  packages/react-ui/src/components/Tag/Tag.stories.tsx
  packages/react-ui/src/components/Tag/index.tsx
  packages/react-ui/src/components/Tag/style.tsx
  packages/react-ui/src/components/Tags/Tags.stories.tsx
  packages/react-ui/src/components/Tags/index.tsx
Labels: feature

#891 Fix typo
  packages/react-ui/src/components/Tag/index.tsx
Labels: documentation

#894 Add readOnly state to Toggle, RadioButton and Checkbox
  packages/react-ui/src/components/Checkbox/Checkbox.stories.tsx
  packages/react-ui/src/components/Checkbox/index.tsx
  packages/react-ui/src/components/RadioButton/RadioButton.stories.tsx
  packages/react-ui/src/components/RadioButton/index.tsx
  packages/react-ui/src/components/RadioButton/style.ts
  packages/react-ui/src/components/Toggle/Toggle.stories.tsx
  packages/react-ui/src/components/Toggle/index.tsx
  packages/react-ui/src/components/form/CheckboxField/CheckboxField.stories.tsx
  packages/react-ui/src/components/form/CheckboxField/index.tsx
Labels: feature

#921 feat(Modal): change internal vertical paddings
  packages/react-ui/src/components/Modal/index.tsx
Labels: enhancement

#924 700 storybook добавить раздел с цветами
  packages/react-ui/src/colors/colors.stories.tsx
  packages/react-ui/src/colors/colorsDescription.tsx
Labels: documentation, feature

#930 feat(TextButton): add iconStart and iconEnd props instead of icon and displayRight
  packages/react-ui/.storybook/main.cjs
  packages/react-ui/.storybook/preview.jsx
  packages/react-ui/package.json
  packages/react-ui/src/components/GroupActionsPane/GroupActionsPane.stories.tsx
  packages/react-ui/src/components/NotificationItem/__snapshots__/NotificationItem.test.tsx.snap
  packages/react-ui/src/components/TextButton/TextButton.stories.tsx
  packages/react-ui/src/components/TextButton/dimensionMixin.ts
  packages/react-ui/src/components/TextButton/index.tsx
  packages/react-ui/src/components/TextButtonMenu/TextButtonMenu.stories.tsx
  packages/react-ui/src/components/TextButtonMenu/index.tsx
  packages/react-ui/src/components/input/Select/Stories/SearchSelect.stories.tsx
  packages/react-ui/src/components/input/Select/Stories/Select.stories.tsx
Labels: enhancement

#935 fix(Menu): fix Menu width
  packages/react-ui/src/components/Menu/index.tsx
Labels: bug

#939 fix(Table): fix problem with onRowClick callback and OverflowMenu
  packages/react-ui/src/components/Table/Row/RowWrapper.tsx
Labels: bug

#948 262 feature table add drag and drop
  packages/react-ui/src/components/Table/HeaderCell.tsx
  packages/react-ui/src/components/Table/RowWidthResizer.tsx
  packages/react-ui/src/components/Table/Stories/Table.stories.tsx
  packages/react-ui/src/components/Table/Stories/Templates/TableColumnDragDrop.tsx
  packages/react-ui/src/components/Table/Stories/Templates/index.tsx
  packages/react-ui/src/components/Table/dragObserver.ts
  packages/react-ui/src/components/Table/icons/cursorGrabbing.svg
  packages/react-ui/src/components/Table/icons/cursorNotAllowed.svg
  packages/react-ui/src/components/Table/index.tsx
  packages/react-ui/src/components/Table/style.ts
Labels: feature
