Repository AdmiralDS/react-ui, pull requests merged in 2023-02, with the labels that each got.

#636 fix(NumberInput): block selecting text on double click
  src/components/input/NumberInput/index.tsx
Labels: bug

#641 fix(Avatar): fix stories controls
  src/components/Avatar/Avatar.stories.tsx
  src/components/AvatarGroup/AvatarGroup.stories.tsx
Labels: documentation

#642 fix(Calendar): fix bug with tooltip and disabled buttons
  src/components/Calendar/components/Panel.tsx
Labels: bug

#649 fix(RadioButton): fix paddings
  src/components/RadioButton/__snapshots__/RadioButton.test.tsx.snap
  src/components/RadioButton/style.ts
Labels: bug

#650 481 notification link
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/components/CheckboxCompositeGroup/__snapshots__/CheckboxCompositeGroup.test.tsx.snap
  src/components/CheckboxGroup/__snapshots__/CheckBoxGroup.test.tsx.snap
  src/components/Link/Link.stories.tsx
  src/components/Link/Link.test.tsx
  src/components/Link/LinkComponent.ts
  src/components/Link/__snapshots__/Link.test.tsx.snap
  src/components/Link/index.tsx
  src/components/Link/mixins.ts
  src/components/MenuButton/__snapshots__/MenuButton.test.tsx.snap
  src/components/MultiButton/__snapshots__/MultiButton.test.tsx.snap
  src/components/Notification/__snapshots__/Notification.test.tsx.snap
  src/components/RadioButton/__snapshots__/RadioButton.test.tsx.snap
  src/components/SelectTree/__snapshots__/SelectTree.test.tsx.snap
  src/components/common/polymorphicProps.ts
  src/components/form/CheckboxField/__snapshots__/CheckboxField.test.tsx.snap
Labels: feature

#651 (fix)Button: add api for icons to fix paddings
  src/components/Button/Button.stories.tsx
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/Button/dimensionMixin.ts
  src/components/Button/index.tsx
  src/components/Button/types.ts
  src/components/MenuButton/__snapshots__/MenuButton.test.tsx.snap
  src/components/MultiButton/__snapshots__/MultiButton.test.tsx.snap
Labels: bug

#653 feat(InputEx): add tooltip
  src/components/input/InputEx/InputEx.stories.tsx
  src/components/input/InputEx/index.tsx
  src/components/input/TextInput/index.tsx
Labels: feature

#658 620 table initial filter activation
  src/components/Table/OverflowMenu.tsx
  src/components/Table/Table.stories.tsx
  src/components/Table/data.tsx
  src/components/Table/filter/Filter.tsx
  src/components/Table/index.tsx
Labels: feature

#669 fix(Button, TextButton): remove focus style after click
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/Button/appearanceMixin/dangerAppearanceMixin.ts
  src/components/Button/appearanceMixin/ghostAppearanceMixin.ts
  src/components/Button/appearanceMixin/primaryAppearanceMixin.ts
  src/components/Button/appearanceMixin/secondaryAppearanceMixin.ts
  src/components/Button/appearanceMixin/successAppearanceMixin.ts
  src/components/Button/appearanceMixin/whiteAppearanceMixin.ts
  src/components/MenuButton/__snapshots__/MenuButton.test.tsx.snap
  src/components/MultiButton/__snapshots__/MultiButton.test.tsx.snap
  src/components/NotificationItem/__snapshots__/NotificationItem.test.tsx.snap
  src/components/TextButton/appearanceMixin.ts
Labels: feature

#670 fix(Tree): expose onMouseLeave event
  src/components/Tree/Tree.stories.tsx
  src/components/Tree/index.tsx
Labels: bug

#671 fix(TabMenu): fix showing overflow menu after updating tabs
  src/components/TabMenu/TabMenu.stories.tsx
  src/components/TabMenu/index.tsx
Labels: bug

#678 665 hint new position types
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/components/CheckboxCompositeGroup/__snapshots__/CheckboxCompositeGroup.test.tsx.snap
  src/components/CheckboxGroup/__snapshots__/CheckBoxGroup.test.tsx.snap
  src/components/Hint/Hint.stories.tsx
  src/components/Hint/index.tsx
  src/components/Hint/style.ts
  src/components/Hint/utils.ts
  src/components/MenuButton/__snapshots__/MenuButton.test.tsx.snap
  src/components/MultiButton/__snapshots__/MultiButton.test.tsx.snap
  src/components/RadioButton/__snapshots__/RadioButton.test.tsx.snap
  src/components/SelectTree/__snapshots__/SelectTree.test.tsx.snap
  src/components/form/CheckboxField/__snapshots__/CheckboxField.test.tsx.snap
Labels: feature

#681 fix(DateTime): fix styles, add Container and Separator components
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/components/CheckboxCompositeGroup/__snapshots__/CheckboxCompositeGroup.test.tsx.snap
  src/components/CheckboxGroup/__snapshots__/CheckBoxGroup.test.tsx.snap
  src/components/MenuButton/MenuButton.stories.tsx
  src/components/MenuButton/__snapshots__/MenuButton.test.tsx.snap
  src/components/MultiButton/__snapshots__/MultiButton.test.tsx.snap
  src/components/RadioButton/__snapshots__/RadioButton.test.tsx.snap
  src/components/SelectTree/__snapshots__/SelectTree.test.tsx.snap
  src/components/form/CheckboxField/__snapshots__/CheckboxField.test.tsx.snap
  src/components/form/DateTimeField/DateTimeField.stories.tsx
  src/components/form/InputField/InputField.stories.tsx
  src/components/input/DateTime/index.tsx
  src/components/input/TextInput/TextInput.stories.tsx
  src/components/input/TextInput/index.tsx
Labels: bug

#682 fix(RadioButton): remove hover circle after click
  src/components/RadioButton/__snapshots__/RadioButton.test.tsx.snap
  src/components/RadioButton/style.ts
Labels: bug

#686 fix(TimeInput): set focus on input when drop menu is opened
  src/components/input/TimeInput/index.tsx
Labels: bug

#693 docs(ReadOnlyMaskedField): add stories example
  src/components/form/ReadOnlyMaskedField/ReadOnlyMaskedField.stories.tsx
Labels: documentation

#694 feat(Spinner): add new size MS 20px
  src/components/Avatar/Avatar.stories.tsx
  src/components/Button/index.tsx
  src/components/Checkbox/Checkbox.stories.tsx
  src/components/Field/Field.stories.tsx
  src/components/IconButton/__snapshots__/IconButton.test.tsx.snap
  src/components/IconButton/index.tsx
  src/components/Spinner/Spinner.stories.tsx
  src/components/Spinner/index.tsx
  src/components/Spinner/svgs/Subtract_ms.svg
  src/components/TextButton/TextButton.stories.tsx
  src/components/TextButton/index.tsx
  src/components/form/CheckboxField/CheckboxField.stories.tsx
  src/components/form/DateField/DateField.stories.tsx
  src/components/form/EditModeField/EditModeField.stories.tsx
  src/components/form/FieldSet/FieldSet.stories.tsx
  src/components/form/FileInputField/FileInputField.stories.tsx
  src/components/form/InputExField/InputExField.stories.tsx
  src/components/form/InputField/InputField.stories.tsx
  src/components/form/NumberInputField/NumberInputField.stories.tsx
  src/components/form/SliderInputField/SliderInputField.stories.tsx
  src/components/form/SliderRangeField/SliderRangeField.stories.tsx
  src/components/form/SuggestField/SuggestField.stories.tsx
  src/components/form/TimeField/TimeField.stories.tsx
  src/components/input/DateInput/DateInput.stories.tsx
  src/components/input/EditMode/EditMode.stories.tsx
  src/components/input/FileInput/FileInput.stories.tsx
  src/components/input/FileInput/FileItem.tsx
  src/components/input/NumberInput/NumberInput.stories.tsx
  src/components/input/PhoneNumberInput/PhoneNumberInput.stories.tsx
  src/components/input/Select/index.tsx
  src/components/input/Select/styled.ts
  src/components/input/SliderInput/SliderInput.stories.tsx
  src/components/input/SliderRange/SliderRange.stories.tsx
  src/components/input/SuggestInput/SuggestInput.stories.tsx
  src/components/input/TextInput/index.tsx
  src/components/input/TimeInput/TimeInput.stories.tsx
Labels: feature
