Repository AdmiralDS/react-ui, pull requests merged in 2023-04, with the labels that each got.

#813 fix(Button): rise icon color specificity
  packages/react-ui/src/components/Button/appearanceMixin/dangerAppearanceMixin.ts
  packages/react-ui/src/components/Button/appearanceMixin/ghostAppearanceMixin.ts
  packages/react-ui/src/components/Button/appearanceMixin/primaryAppearanceMixin.ts
  packages/react-ui/src/components/Button/appearanceMixin/secondaryAppearanceMixin.ts
  packages/react-ui/src/components/Button/appearanceMixin/successAppearanceMixin.ts
  packages/react-ui/src/components/Button/appearanceMixin/whiteAppearanceMixin.ts
Labels: bug

#818 feat(Avatar): move showTooltip prop from internal to usual props
  packages/react-ui/src/components/Avatar/index.tsx
Labels: feature

#834 docs(Toast): fix docs
  packages/react-ui/src/components/Toast/Toast.stories.tsx
Labels: documentation

#835 fix(TabMenu): fix press Tab style
  packages/react-ui/src/components/TabMenu/__snapshots__/TabMenu.test.tsx.snap
  packages/react-ui/src/components/TabMenu/style.ts
Labels: bug

#836 fix(Table): fix bug with OverflowMenu mouseenter and row hover state
  packages/react-ui/src/components/Table/OverflowMenu.tsx
  packages/react-ui/src/components/Table/Row/RowWrapper.tsx
  packages/react-ui/src/components/Table/Table.stories.tsx
  packages/react-ui/src/components/Table/index.tsx
  packages/react-ui/src/components/Table/style.ts
Labels: bug

#840 docs(IconPlacement,Link): fix docs
  packages/react-ui/src/components/IconPlacement/IconPlacement.stories.tsx
  packages/react-ui/src/components/Link/Link.stories.tsx
Labels: documentation

#841 fix(StatusIndicator): fix docs, add playground
  packages/react-ui/src/components/StatusIndicator/StatusIndicator.stories.tsx
Labels: documentation

#846 fix(Tag): fix problem with props description
  packages/react-ui/src/components/Tag/Tag.stories.tsx
  packages/react-ui/src/components/Tag/index.tsx
  packages/react-ui/src/components/Tag/style.tsx
Labels: documentation

#852 docs(SuggestField): fix control type
  packages/react-ui/src/components/form/SuggestField/SuggestField.stories.tsx
Labels: documentation

#853 docs(ProgressPage): add label control
  packages/react-ui/src/components/ProgressPage/ProgressPage.stories.tsx
Labels: documentation

#858 fix(DateInput): fix stories controls
  packages/react-ui/src/components/input/DateInput/DateInput.stories.tsx
  packages/react-ui/src/components/input/DateInput/index.tsx
Labels: documentation

#863 feat(Breadcrumbs): add lastBreadcrumbActive prop to control active-in…
  packages/react-ui/src/components/Breadcrumbs/BreadCrumb.tsx
  packages/react-ui/src/components/Breadcrumbs/Breadcrumbs.stories.tsx
  packages/react-ui/src/components/Breadcrumbs/index.tsx
Labels: bug, feature

#864 fix(ContentSwitcher): fix storybook docs, place playground story on 1…
  packages/react-ui/src/components/ContentSwitcher/ContentSwitcher.stories.tsx
Labels: documentation

#876 fix(Table): fix onRowClick trigger when user clicks ExpandIcon
  packages/react-ui/src/components/Table/Row/RegularRow.tsx
Labels: bug

#877 docs(SelectField): fix control types
  packages/react-ui/src/components/form/SelectField/SelectField.stories.tsx
Labels: documentation

#882 fix(Chips): fix behavior and hover style
  packages/react-ui/src/components/Chips/Chips.stories.tsx
  packages/react-ui/src/components/Chips/index.tsx
  packages/react-ui/src/components/Chips/style.ts
Labels: bug

#883 820 class name style modal
  packages/react-ui/src/components/Modal/Modal.stories.tsx
  packages/react-ui/src/components/Modal/index.tsx
Labels: feature

#884 docs(Menu): add example with additional text and icons
  packages/react-ui/src/components/Menu/Stories/Menu.stories.tsx
  packages/react-ui/src/components/Menu/Stories/Templates/IconsAndAdditionalText.tsx
  packages/react-ui/src/components/Menu/Stories/Templates/index.ts
  packages/react-ui/src/components/Menu/index.tsx
Labels: documentation

#885 822 pagination two search page
  packages/react-ui/src/components/PaginationTwo/PaginationTwo.stories.tsx
  packages/react-ui/src/components/PaginationTwo/index.tsx
Labels: bug
