Repository AdmiralDS/react-ui, pull requests merged in 2023-10, with the labels that each got.

#1131 docs(DateField, DateInput): pass placeholder to templates
  src/components/form/DateField/stories/DateFieldBase.template.tsx
  src/components/input/DateInput/stories/DateInputAlternativeIcon.template.tsx
  src/components/input/DateInput/stories/DateInputPickMonth.template.tsx
  src/components/input/DateInput/stories/DateInputPlayground.template.tsx
  src/components/input/DateInput/stories/DateInputSpecialDates.template.tsx
Labels: documentation

#1132 1084 table expandedrowrenderer contentmaxheight
  src/components/Table/Row/ExpandedRow.tsx
  src/components/Table/Row/RowWrapper.tsx
  src/components/Table/Row/Transition.tsx
  src/components/Table/style.ts
Labels: bug

#1133 docs(DateTimeField): pass props to stories templates
  src/components/form/DateTimeField/stories/DateTimeField.stories.tsx
  src/components/form/DateTimeField/stories/DateTimeFieldBase.template.tsx
  src/components/form/DateTimeField/stories/DateTimeFieldDisabled.template.tsx
  src/components/form/DateTimeField/stories/DateTimeFieldReadOnly.template.tsx
  src/components/form/DateTimeField/stories/DateTimeFieldStatus.template.tsx
Labels: documentation

#1134 1112 storybook fileinput прокинуть размеры в примеры
  src/components/form/FileInputField/index.tsx
  src/components/form/FileInputField/stories/FileInputField.stories.tsx
  src/components/input/FileInput/index.tsx
  src/components/input/FileInput/stories/FileInput.stories.tsx
Labels: documentation

#1138 1136 locales refactor view code
  src/components/locale.stories.tsx
  src/locales/LocaleProp.template.tsx
  src/locales/LocaleThemeCurrentLocale.template.tsx
  src/locales/LocaleThemeNewLocale.template.tsx
  src/locales/locale.stories.tsx
Labels: documentation

#1141 feat(PseudoIcon, PseudoText): поддержка styled-components v6
  src/components/skeleton/PseudoIcon.ts
  src/components/skeleton/PseudoIcon.tsx
  src/components/skeleton/PseudoText.ts
  src/components/skeleton/PseudoText.tsx
Labels: feature

#1157 feat(Badge): change padding in size M
  src/components/Badge/__snapshots__/Badge.test.tsx.snap
  src/components/Badge/index.tsx
Labels: feature

#1166 feat(Accordion, Chips, ContentSwitcher, PaginationOne): add press state
  src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
  src/components/Accordion/style.ts
  src/components/Chips/style.ts
  src/components/ContentSwitcher/ContentSwitcherItem.tsx
  src/components/ContentSwitcher/__snapshots__/ContentSwitcher.test.tsx.snap
  src/components/PaginationOne/PaginationButton.tsx
Labels: feature
