Repository AdmiralDS/react-ui, pull requests merged in 2023-07, with the labels that each got.

#991 fix ts mistakes in Slider and Range components
  src/components/Range/utils.ts
  src/components/Slider/index.tsx
  src/components/Slider/utils.ts
  src/components/Tooltip/Stories/Tooltip.stories.tsx
  src/components/input/NumberInput/index.tsx
Labels: bug

#1005 fix(InputEx): размер компонента также влияет на размер выпадающего меню
  src/components/input/InputEx/Menu.tsx
  src/components/input/InputEx/SuffixSelect.tsx
  src/components/input/InputEx/index.tsx
Labels: bug

#1014 docs(Button): fix stories
  src/components/Button/Stories/Button.stories.tsx
Labels: documentation

#1016 docs(RadioButton): fix story
  src/components/RadioButton/Stories/Templates/RadioButtonPlayground.tsx
Labels: documentation

#1026 992 storybook refactor subcomponents api
  src/components/Tooltip/Stories/Templates/TooltipDelay.tsx
  src/components/Tooltip/Stories/Templates/TooltipHocBase.tsx
  src/components/Tooltip/Stories/Templates/TooltipHocClass.tsx
  src/components/Tooltip/Stories/Templates/TooltipHocFC.tsx
  src/components/Tooltip/Stories/Templates/TooltipMenuButton.tsx
  src/components/Tooltip/Stories/Templates/TooltipRef.tsx
  src/components/Tooltip/Stories/Templates/index.tsx
  src/components/Tooltip/Stories/Tooltip.stories.tsx
  src/components/TooltipHOC/Stories/Templates/TooltipHocBase.tsx
  src/components/TooltipHOC/Stories/Templates/TooltipHocClass.tsx
  src/components/TooltipHOC/Stories/Templates/TooltipHocFC.tsx
  src/components/TooltipHOC/Stories/Templates/TooltipHocRef.tsx
  src/components/TooltipHOC/Stories/Templates/TooltipHocRefSetter.tsx
  src/components/TooltipHOC/Stories/Templates/index.tsx
  src/components/TooltipHOC/Stories/TooltipHOCStory.tsx
  src/components/TooltipHOC/Stories/TooltipHoc.stories.tsx
Labels: documentation

#1039 docs(PhoneNumberInput): fix story
  src/components/input/PhoneNumberInput/Stories/PhoneNumberInput.stories.tsx
  src/components/input/PhoneNumberInput/index.tsx
Labels: documentation

#1047 985 datatable row status
  src/components/Table/Row/RowWrapper.tsx
  src/components/Table/Stories/Table.stories.tsx
  src/components/Table/Stories/Templates/TableRowState.tsx
  src/components/Table/index.tsx
  src/components/Table/mixins.ts
  src/components/Table/style.ts
  src/components/TooltipHOC/Stories/TooltipHOCStory.tsx
  src/components/TooltipHOC/Stories/TooltipHoc.stories.tsx
Labels: feature

#1053 1049 editmodefield редактировать пустое поле вписать что то нажать отмену остаётся первая буква
  src/components/input/EditMode/Stories/EditMode.stories.tsx
  src/components/input/EditMode/index.tsx
Labels: bug

#1063 1040 docs storybook fix stories
  src/components/TagMenu/Stories/Templates/TagMenuPlayground.tsx
  src/components/TagMenu/Stories/Templates/TagMenuSizes.tsx
Labels: documentation
