Repository AdmiralDS/react-ui, pull requests merged in 2023-08, with the labels that each got.

#1064 docs(Hint): добавлен пример с заголовком в контенте Hint
  src/components/Hint/Stories/Hint.stories.tsx
  src/components/Hint/Stories/Templates/HintWithHeader.tsx
  src/components/Hint/Stories/Templates/index.tsx
Labels: documentation

#1066 1065 table onrowclick expandicon group
  src/components/Table/Row/GroupRow.tsx
  src/components/Table/index.tsx
  src/components/Table/types.ts
Labels: bug

#1069 feat(Modal): добавлена статусная иконка
  src/components/Hint/Stories/Templates/index.tsx
  src/components/Hint/stories/Hint.stories.tsx
  src/components/Hint/stories/HintAnchorCss.template.tsx
  src/components/Hint/stories/HintBase.template.tsx
  src/components/Hint/stories/HintClassName.template.tsx
  src/components/Hint/stories/HintClick.template.tsx
  src/components/Hint/stories/HintPosition.template.tsx
  src/components/Hint/stories/HintTarget.template.tsx
  src/components/Hint/stories/HintTextButton.template.tsx
  src/components/Hint/stories/HintWithHeader.template.tsx
  src/components/Modal/Stories/Templates/index.tsx
  src/components/Modal/index.tsx
  src/components/Modal/stories/Modal.stories.tsx
  src/components/Modal/stories/ModalCustomContent.template.tsx
  src/components/Modal/stories/ModalCustomOverlay.template.tsx
  src/components/Modal/stories/ModalOneButton.template.tsx
  src/components/Modal/stories/ModalScroll.template.tsx
  src/components/Modal/stories/ModalStatusIcon.template.tsx
  src/components/Modal/stories/ModalTwoButtons.template.tsx
  src/components/Modal/stories/ModalWithoutButtons.template.tsx
  src/components/input/DateInput/stories/DateInput.stories.tsx
  src/components/input/DateInput/stories/DateInputAlternativeIcon.template.tsx
  src/components/input/DateInput/stories/DateInputPickMonth.template.tsx
  src/components/input/DateInput/stories/DateInputPlayground.template.tsx
  src/components/input/DateInput/stories/DateInputSpecialDates.template.tsx
Labels: feature

#1070 1029 table react 17 cant perform a react state update
  src/components/common/observeRect.ts
Labels: bug

#1085 970 targetref targetelement
  src/components/Chips/index.tsx
  src/components/DropMenu/index.tsx
  src/components/Dropdown/index.tsx
  src/components/DropdownContainer/index.tsx
  src/components/DropdownContainer/stories/DropDownContainer.stories.tsx
  src/components/DropdownContainer/stories/MenuContainer.template.tsx
  src/components/DropdownContainer/stories/SimpleContainer.template.tsx
  src/components/GroupActionsPane/ColumnsButton.tsx
  src/components/GroupActionsPane/SettingsButton.tsx
  src/components/Hint/index.tsx
  src/components/Hint/stories/Hint.stories.tsx
  src/components/Hint/stories/HintTarget.template.tsx
  src/components/Menu/SubMenuContainer.tsx
  src/components/Pill/stories/PillWithTooltip.template.tsx
  src/components/PositionInPortal.tsx
  src/components/Stepper/StepContent.tsx
  src/components/Table/HeaderCell.tsx
  src/components/Table/TitleText.tsx
  src/components/Table/filter/Filter.tsx
  src/components/Tag/index.tsx
  src/components/Tooltip/Tooltip.test.tsx
  src/components/Tooltip/index.tsx
  src/components/Tooltip/stories/Tooltip.stories.tsx
  src/components/Tooltip/stories/TooltipBase.template.tsx
  src/components/Tooltip/stories/TooltipDelay.template.tsx
  src/components/Tooltip/stories/TooltipMenuButton.template.tsx
  src/components/Tooltip/stories/TooltipRef.template.tsx
  src/components/TooltipHOC/index.tsx
  src/components/input/DateInput/index.tsx
  src/components/input/EditMode/index.tsx
  src/components/input/FileInput/FileItem.tsx
  src/components/input/FileUploader/FileInfo.tsx
  src/components/input/InputEx/SuffixSelect.tsx
  src/components/input/InputEx/index.tsx
  src/components/input/PhoneNumberInput/CountryBlock.tsx
  src/components/input/PhoneNumberInput/index.tsx
  src/components/input/Select/DisplayValue.tsx
  src/components/input/Select/MultipleSelectChips/CounterChip.tsx
  src/components/input/Select/index.tsx
  src/components/input/SuggestInput/index.tsx
  src/components/input/TextInput/index.tsx
  src/components/input/TimeInput/index.tsx
Labels: refactor

#1089 1078 bug sliderinput controlled
  src/components/input/SliderInput/index.tsx
Labels: bug
