Repository AdmiralDS/react-ui, pull requests merged in 2024-04, with the labels that each got.

#1294 1289 bug breadcrumbs скачет верстка при переключении
  src/components/Breadcrumbs/Menu.tsx
  src/components/Breadcrumbs/index.tsx
  src/components/Breadcrumbs/style.ts
Labels: enhancement

#1300 feat(FileInput): добавлен формат файла ZIP
  src/components/input/FileInput/stories/FileInputWithStatus.template.tsx
  src/components/input/FileInput/utils.ts
Labels: feature

#1311 1283 bug warning resizeobserver table
  src/components/Drawer/components.tsx
  src/components/Modal/index.tsx
  src/components/TabMenu/index.tsx
  src/components/Table/HeaderCell.tsx
  src/components/Table/index.tsx
  src/components/common/utils/debounce.ts
Labels: bug

#1313 1309 feature button добавить опцию включения бейджей
  src/components/Badge/index.tsx
  src/components/Button/stories/Button.stories.tsx
  src/components/Button/stories/ButtonPlayground.template.tsx
  src/components/Button/stories/ButtonWithBadge.template.tsx
Labels: feature

#1316 1315 fix test warnings
  src/components/Chips/Chips.test.tsx
  src/components/Hint/Hint.test.tsx
  src/components/Tooltip/Tooltip.test.tsx
  src/components/form/DateField/DateField.test.tsx
  src/components/input/Select/Select.test.tsx
  src/components/input/SuggestInput/SuggestInput.test.tsx
Labels: documentation
