Repository AdmiralDS/react-ui, pull requests merged in 2024-03, with the labels that each got.

#1263 1261 input добавить пример с информером
  src/components/Hint/HintContainer.tsx
  src/components/Hint/index.tsx
  src/components/Hint/stories/HintClick.template.tsx
  src/components/form/DateField/__snapshots__/DateField.test.tsx.snap
  src/components/form/InputField/stories/InputFieldInput.template.tsx
  src/components/input/TextInput/index.tsx
Labels: documentation

#1275 1272 button не работает проперти title
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/Button/index.tsx
  src/components/FloatingButton/FloatingButtonMenu.tsx
  src/components/FloatingButton/style.tsx
  src/components/IconButton/__snapshots__/IconButton.test.tsx.snap
  src/components/IconButton/index.tsx
  src/components/IconPlacement/index.tsx
  src/components/Link/LinkComponent.ts
  src/components/Link/__snapshots__/Link.test.tsx.snap
  src/components/Link/index.tsx
  src/components/Link/mixins.ts
  src/components/MenuButton/__snapshots__/MenuButton.test.tsx.snap
  src/components/MultiButton/__snapshots__/MultiButton.test.tsx.snap
  src/components/Notification/__snapshots__/Notification.test.tsx.snap
  src/components/NotificationItem/__snapshots__/NotificationItem.test.tsx.snap
  src/components/OverflowMenu/__snapshots__/OverflowMenu.test.tsx.snap
  src/components/TabMenu/__snapshots__/TabMenu.test.tsx.snap
Labels: bug

#1287 Number input refactor api
  src/components/Slider/TickMarks.tsx
  src/components/Slider/index.tsx
  src/components/form/NumberInputField/stories/NumberInputFieldPlayground.template.tsx
  src/components/form/SliderInputField/stories/SliderInputField.stories.tsx
  src/components/form/SliderRangeField/stories/SliderRangeField.stories.tsx
  src/components/input/NumberInput/AutoSizeInput.tsx
  src/components/input/NumberInput/index.tsx
  src/components/input/NumberInput/stories/NumberInputControlled.template.tsx
  src/components/input/NumberInput/stories/NumberInputCustomised.template.tsx
  src/components/input/NumberInput/stories/NumberInputDisabled.template.tsx
  src/components/input/NumberInput/stories/NumberInputMinMax.template.tsx
  src/components/input/NumberInput/stories/NumberInputPlayground.template.tsx
  src/components/input/NumberInput/utils.ts
  src/components/input/SliderInput/index.tsx
  src/components/input/SliderInput/stories/SliderInput.stories.tsx
  src/components/input/SliderInput/stories/SliderInputCustomised.template.tsx
  src/components/input/SliderRange/index.tsx
  src/components/input/SliderRange/stories/SliderRange.stories.tsx
  src/components/input/SliderRange/stories/SliderRangeControlled.template.tsx
  src/components/input/SliderRange/stories/SliderRangeCustom.template.tsx
Labels: refactor
