Repository AdmiralDS/react-ui, pull requests merged in 2024-09, with the labels that each got.

#1470 1432 feature segmented control
  src/components/Badge/index.tsx
  src/components/SegmentedControl/SegmentedControlItem.tsx
  src/components/SegmentedControl/index.tsx
  src/components/SegmentedControl/mixins.ts
  src/components/SegmentedControl/stories/SegmentedControl.stories.tsx
  src/components/SegmentedControl/stories/SegmentedControlAppearance.template.tsx
  src/components/SegmentedControl/stories/SegmentedControlCheckbox.template.tsx
  src/components/SegmentedControl/stories/SegmentedControlDimension.template.tsx
  src/components/SegmentedControl/stories/SegmentedControlPlayground.template.tsx
  src/components/SegmentedControl/stories/SegmentedControlRadio.template.tsx
  src/components/SegmentedControl/stories/SegmentedControlState.template.tsx
  src/components/SegmentedControl/stories/SegmentedControlVariants.template.tsx
  src/components/SegmentedControl/style.ts
  src/components/Table/stories/TableColumnDragDrop.template.tsx
  src/components/Table/stories/TableMultiline.template.tsx
  src/components/Table/stories/TableRowState.template.tsx
  src/components/form/FieldSet/stories/FieldSetRadioButton.template.tsx
  src/index.ts
Labels: feature

#1473 improve story with custom option, custom option styles depend on dime…
  src/components/Menu/stories/MenuWithCustomItems.template.tsx
Labels: documentation

#1475 fix(PaginationOne): #1474 исправлен размер кнопок со стрелками
  src/components/PaginationOne/index.tsx
Labels: bug

#1477 1469 tabmenu иногда подсветка активной табы находится левее самой табы
  src/components/TabMenuComponent/tabMenus/CardTabMenuHorizontal.tsx
  src/components/TabMenuComponent/tabMenus/TabMenuHorizontal.tsx
  src/components/TabMenuComponent/tabMenus/TabMenuIcon.tsx
Labels: bug

#1488 1359 dropdowncontainer position refactor
  src/components/DropdownContainer/index.tsx
  src/components/DropdownContainer/utils.ts
Labels: feature

#1490 feat(Carousel): добавлен новый компонент
  src/components/Carousel/CarouselButton.tsx
  src/components/Carousel/index.tsx
  src/components/Carousel/stories/Carousel.stories.tsx
  src/components/Carousel/stories/CarouselAutoChange.template.tsx
  src/components/Carousel/stories/CarouselPlayground.template.tsx
  src/index.ts
Labels: feature

#1491 feat(Theme): обновление токенов в соответствии с ДС
  src/colors/colorsDescription.tsx
  src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
  src/components/Badge/__snapshots__/Badge.test.tsx.snap
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/CSSCustomProps/darkTheme.ts
  src/components/CSSCustomProps/lightTheme.ts
  src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/components/CheckboxCompositeGroup/__snapshots__/CheckboxCompositeGroup.test.tsx.snap
  src/components/CheckboxGroup/__snapshots__/CheckBoxGroup.test.tsx.snap
  src/components/Chips/__snapshots__/Chips.test.tsx.snap
  src/components/ContentSwitcher/__snapshots__/ContentSwitcher.test.tsx.snap
  src/components/DropDownMenu/__snapshots__/DropDown.test.tsx.snap
  src/components/IconButton/__snapshots__/IconButton.test.tsx.snap
  src/components/MenuButton/__snapshots__/MenuButton.test.tsx.snap
  src/components/MultiButton/__snapshots__/MultiButton.test.tsx.snap
  src/components/Notification/__snapshots__/Notification.test.tsx.snap
  src/components/NotificationItem/__snapshots__/NotificationItem.test.tsx.snap
  src/components/OverflowMenu/__snapshots__/OverflowMenu.test.tsx.snap
  src/components/ProgressPage/__snapshots__/ProgressPage.test.tsx.snap
  src/components/ProgressStepper/__snapshots__/ProgressStepper.test.tsx.snap
  src/components/RadioButton/__snapshots__/RadioButton.test.tsx.snap
  src/components/SelectTree/__snapshots__/SelectTree.test.tsx.snap
  src/components/Stepper/__snapshots__/Stepper.test.tsx.snap
  src/components/TabMenu/__snapshots__/TabMenu.test.tsx.snap
  src/components/Tag/__snapshots__/Tag.test.tsx.snap
  src/components/Tags/__snapshots__/Tags.test.tsx.snap
  src/components/Toggle/__snapshots__/Toggle.test.tsx.snap
  src/components/form/CheckboxField/__snapshots__/CheckboxField.test.tsx.snap
  src/components/form/DateField/__snapshots__/DateField.test.tsx.snap
  src/components/themes/common/color/interfaces.ts
  src/components/themes/common/opacity.ts
  src/components/themes/dark/color.ts
  src/components/themes/dark/opacity.ts
  src/components/themes/light/color.ts
  src/components/themes/light/opacity.ts
Labels: feature

#1493 fix(Chips): исправлены размеры при appearance=outlined
  src/components/Chips/__snapshots__/Chips.test.tsx.snap
  src/components/Chips/style.ts
Labels: bug

#1494 feat(Chips): фоновый цвет при appearance=filled изменен на группу Opacity
  src/components/Chips/index.tsx
  src/components/Chips/style.ts
Labels: feature

#1496 feat(Table): #1480 фоновый цвет серых хедера и строк таблицы изменён …
  src/components/Table/mixins.ts
  src/components/Table/style.ts
Labels: feature

#1499 1497 iconbutton invisible icon
  src/components/IconButton/__snapshots__/IconButton.test.tsx.snap
  src/components/IconButton/index.tsx
  src/components/Spinner/Subtract.svg
Labels: bug

#1508 1460 design review компоненты в состоянии loading не должны реагировать на курсор
  src/components/Button/index.tsx
  src/components/IconButton/index.tsx
  src/components/InputIconButton.tsx
  src/components/MenuButton/__snapshots__/MenuButton.test.tsx.snap
  src/components/MenuButton/stories/MenuButton.stories.tsx
  src/components/MultiButton/__snapshots__/MultiButton.test.tsx.snap
  src/components/OpenStatusButton.tsx
  src/components/Tree/TreeNode.tsx
  src/components/form/DateField/__snapshots__/DateField.test.tsx.snap
  src/components/input/EditMode/index.tsx
  src/components/input/EditMode/stories/EditMode.stories.tsx
  src/components/input/EditModeArea/stories/EditModeArea.stories.tsx
  src/components/input/FileInput/FileItem.tsx
  src/components/input/NumberInput/index.tsx
  src/components/input/NumberInput/stories/NumberInput.stories.tsx
  src/components/input/PhoneNumberInput/index.tsx
  src/components/input/Select/index.tsx
  src/components/input/Select/styled.ts
  src/components/input/SliderInput/index.tsx
  src/components/input/SliderInput/stories/SliderInput.stories.tsx
  src/components/input/SuggestInput/stories/SuggestInputPlayground.template.tsx
  src/components/input/TextInput/index.tsx
Labels: feature

#1513 1429 feature typography добавлены дефолтные стили текста
  src/components/Carousel/CarouselButton.tsx
  src/components/Typography/defaultTypographyMixin.ts
  src/components/Typography/index.ts
  src/components/Typography/stories/DefaultTypography.stories.tsx
  src/components/Typography/stories/UsingDefaultTypographyGlobally.template.tsx
  src/components/Typography/stories/UsingDefaultTypographyLocally.template.tsx
Labels: feature

#1525 1414 feature list
  src/components/List/OrderedList.tsx
  src/components/List/UnorderedList.tsx
  src/components/List/index.tsx
  src/components/List/stories/List.stories.tsx
  src/components/List/stories/ListMarkerColor.template.tsx
  src/components/List/stories/ListMultiline.template.tsx
  src/components/List/stories/ListNested.template.tsx
  src/components/List/stories/OrderedList.stories.tsx
  src/components/List/stories/OrderedListPlayground.template.tsx
  src/components/List/stories/OrderedListVariants.template.tsx
  src/components/List/stories/UnorderedList.stories.tsx
  src/components/List/stories/UnorderedListPlayground.template.tsx
  src/components/List/stories/UnorderedListVariants.template.tsx
  src/components/List/style.ts
  src/index.ts
Labels: feature

#1526 feat(List): #1521 добавлена возможность кастомизации маркеров через п…
  src/components/List/OrderedList.tsx
  src/components/List/UnorderedList.tsx
  src/components/List/stories/List.stories.tsx
  src/components/List/stories/ListMarkerCustom.template.tsx
  src/components/List/stories/OrderedList.stories.tsx
  src/components/List/stories/UnorderedList.stories.tsx
  src/components/List/style.ts
Labels: feature
