Repository AdmiralDS/react-ui, pull requests merged in 2024-11, with the labels that each got.

#1559 1547 feature theme изменить токены neutral 00 и neutral 05
  src/components/AvatarBase/useLoaded.ts
  src/components/Badge/Badge.test.tsx
  src/components/Breadcrumbs/index.tsx
  src/components/Calendar/components/Month.tsx
  src/components/Calendar/components/Months.tsx
  src/components/Calendar/components/Panel.tsx
  src/components/Calendar/components/Week.tsx
  src/components/Calendar/components/Years.tsx
  src/components/Calendar/date-utils.ts
  src/components/Calendar/index.tsx
  src/components/Calendar/stories/CalendarSimple.template.tsx
  src/components/Calendar/stories/Range.template.tsx
  src/components/Calendar/stories/SimpleWithChangeViewDate.template.tsx
  src/components/Calendar/stories/SimpleWithFilterDate.template.tsx
  src/components/Calendar/stories/SimpleWithMaxDate.template.tsx
  src/components/Calendar/stories/SimpleWithSetActiveViewDate.template.tsx
  src/components/Calendar/stories/SimpleWithSetActiveViewDateAfterChooseYear.template.tsx
  src/components/Calendar/stories/SimpleWithSetActiveViewWithoutDay.template.tsx
  src/components/Calendar/stories/SimpleWithSpecialDates.template.tsx
  src/components/TabMenu/index.tsx
  src/components/Table/drag/ColumnDrag.tsx
  src/components/input/SliderRange/stories/SliderRangeControlled.template.tsx
  src/components/input/SliderRange/stories/SliderRangeCustom.template.tsx
  src/components/input/SliderRange/stories/SliderRangePlayground.template.tsx
  src/components/themes/dark/color.ts
Labels: feature

#1563 1411 feature imageviewer
  src/components/DropMenu/stories/DropMenuCategory.template.tsx
  src/components/GroupActionsPane/ColumnsButton.tsx
  src/components/GroupActionsPane/index.tsx
  src/components/GroupActionsPane/stories/PaneSimple.template.tsx
  src/components/ImageViewer/ImageCounter.tsx
  src/components/ImageViewer/ImageMiniature.tsx
  src/components/ImageViewer/ImagePreview.tsx
  src/components/ImageViewer/ImageViewerCloseButton.tsx
  src/components/ImageViewer/ImageViewerToolbar.tsx
  src/components/ImageViewer/ImageViewerToolbarButton.tsx
  src/components/ImageViewer/constants.ts
  src/components/ImageViewer/index.tsx
  src/components/ImageViewer/stories/ImageViewer.stories.tsx
  src/components/ImageViewer/stories/ImageViewerMobile.template.tsx
  src/components/ImageViewer/stories/ImageViewerPlayground.template.tsx
  src/components/ImageViewer/stories/Service.svg
  src/components/ImageViewer/types.ts
  src/components/ImageViewer/utils.ts
  src/components/Menu/stories/MenuCardGroups.template.tsx
  src/components/OverflowMenu/stories/OverflowMenuBase.template.tsx
  src/components/OverflowMenu/stories/OverflowMenuOptions.template.tsx
  src/components/OverflowMenu/stories/OverflowMenuSizesOrientation.template.tsx
  src/components/Pill/stories/PillMenu.template.tsx
  src/components/Pill/stories/PillNested.template.tsx
  src/components/Pill/stories/PillSimple.template.tsx
  src/components/Pill/stories/PillWithTooltip.template.tsx
  src/components/ProgressStepper/stories/ProgressStepperVariants.template.tsx
  src/components/T/stories/TFontsDemo.template.tsx
  src/components/T/stories/storyDescriptions.ts
  src/components/form/EditModeAreaField/stories/EditModeAreaFieldErrorState.template.tsx
  src/components/form/EditModeAreaField/stories/EditModeAreaFieldExtraText.template.tsx
  src/components/form/EditModeField/stories/EditModeFieldExtraText.template.tsx
  src/components/themes/common/locales.ts
  src/index.ts
  src/locales/LocaleThemeNewLocale.template.tsx
Labels: feature

#1565 docs(FileInput): добавлен пример с кастомными типами файлов
  src/components/input/FileInput/stories/FileInput.stories.tsx
  src/components/input/FileInput/stories/FileInputCustomFileType.template.tsx
Labels: documentation

#1572 feat(theme): изменен токен 'Opacity/Modal' в светлой теме
  src/colors/colorsDescription.tsx
  src/components/CSSCustomProps/lightTheme.ts
  src/components/themes/light/color.ts
  src/components/themes/light/opacity.ts
Labels: feature

#1576 1568 table callback on dragdrop end
  src/components/Table/drag/ColumnDrag.tsx
  src/components/Table/drag/RowDrag.tsx
  src/components/Table/dragObserver.ts
  src/components/Table/index.tsx
  src/components/Table/stories/TableColumnDragDrop.template.tsx
  src/components/Table/stories/TableRowDragDrop.template.tsx
  src/components/Table/types.ts
Labels: feature

#1578 feat(Theme): #1577 в темной теме изменены значения css переменных Ne…
  src/components/CSSCustomProps/darkTheme.ts
Labels: feature

#1587 fix(Hint): базовые html-атрибуты прокидываются непосредственно на эле…
  src/components/Hint/HintContainer.tsx
Labels: bug
