Repository AdmiralDS/react-ui, pull requests merged in 2024-07, with the labels that each got.

#1371 1339 refactor tabmenu
  src/components/DropMenu/index.tsx
  src/components/TabMenu/index.tsx
  src/components/TabMenu/stories/TabMenu.stories.tsx
  src/components/TabMenuComponent/constants.ts
  src/components/TabMenuComponent/containerElements/ActiveHorizontalTabSelector.tsx
  src/components/TabMenuComponent/containerElements/ActiveVerticalTabSelector.tsx
  src/components/TabMenuComponent/containerElements/HorizontalTabOverflowMenu.tsx
  src/components/TabMenuComponent/containerElements/SlideArrowButton.tsx
  src/components/TabMenuComponent/containerElements/VerticalTabOverflowMenu.tsx
  src/components/TabMenuComponent/containerElements/index.ts
  src/components/TabMenuComponent/containerElements/types.ts
  src/components/TabMenuComponent/containers/HorizontalTabMenuContainer.tsx
  src/components/TabMenuComponent/containers/HorizontalTabsContainer.tsx
  src/components/TabMenuComponent/containers/IconTabMenuContainer.tsx
  src/components/TabMenuComponent/containers/VerticalTabMenuContainer.tsx
  src/components/TabMenuComponent/containers/index.ts
  src/components/TabMenuComponent/index.ts
  src/components/TabMenuComponent/stories/horizontalTabMenuStories/TabMenuHorizontal.stories.tsx
  src/components/TabMenuComponent/stories/horizontalTabMenuStories/TabMenuHorizontalTemplate.tsx
  src/components/TabMenuComponent/stories/horizontalTabsStories/HorizontalTabs.stories.tsx
  src/components/TabMenuComponent/stories/horizontalTabsStories/HorizontalTabsTemplate.tsx
  src/components/TabMenuComponent/stories/iconTabMenuStories/IconTabMenu.stories.tsx
  src/components/TabMenuComponent/stories/iconTabMenuStories/IconTabMenuTemplate.tsx
  src/components/TabMenuComponent/stories/verticalTabMenuStories/VerticalTabMenu.stories.tsx
  src/components/TabMenuComponent/stories/verticalTabMenuStories/VerticalTabMenuTemplate.tsx
  src/components/TabMenuComponent/tabElements/TabBadge.tsx
  src/components/TabMenuComponent/tabElements/TabIcon.tsx
  src/components/TabMenuComponent/tabElements/TabText.tsx
  src/components/TabMenuComponent/tabElements/index.ts
  src/components/TabMenuComponent/tabMenus/HorizontalTabs.tsx
  src/components/TabMenuComponent/tabMenus/TabMenuHorizontal.tsx
  src/components/TabMenuComponent/tabMenus/TabMenuIcon.tsx
  src/components/TabMenuComponent/tabMenus/TabMenuVertical.tsx
  src/components/TabMenuComponent/tabMenus/index.ts
  src/components/TabMenuComponent/tabs/BaseTab.tsx
  src/components/TabMenuComponent/tabs/HorizontalTab.tsx
  src/components/TabMenuComponent/tabs/IconTab.tsx
  src/components/TabMenuComponent/tabs/VerticalTab.tsx
  src/components/TabMenuComponent/tabs/index.ts
  src/components/TabMenuComponent/types.ts
  src/components/TabMenuComponent/utils.ts
  src/index.ts
Labels: feature

#1373 feat(Colors): добавлены новые токены Opacity
  src/colors/colorsDescription.tsx
  src/components/CSSCustomProps/darkTheme.ts
  src/components/CSSCustomProps/lightTheme.ts
  src/components/themes/common/color/interfaces.ts
  src/components/themes/common/opacity.ts
  src/components/themes/dark/color.ts
  src/components/themes/dark/opacity.ts
  src/components/themes/light/color.ts
  src/components/themes/light/opacity.ts
Labels: feature

#1374 845 table virtual scroll dynamic row height
  src/components/Table/index.tsx
  src/components/Table/stories/Table.stories.tsx
  src/components/Table/stories/TableDynamicVirtualScroll.template.tsx
  src/components/Table/stories/TableFixedVirtualScroll.template.tsx
  src/components/Table/style.ts
  src/components/Table/types.ts
  src/components/Table/virtualScroll/DynamicSizeBody.tsx
  src/components/Table/virtualScroll/FixedSizeBody.tsx
  src/components/Table/virtualScroll/VirtualRowWrapper.tsx
  src/components/Table/virtualScroll/index.ts
  src/components/Table/virtualScroll/utils.ts
Labels: feature

#1375 1364 feature button multibutton menubutton добавлен новый appearance tertiary
  src/components/Badge/index.tsx
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/Button/appearanceMixin/index.ts
  src/components/Button/appearanceMixin/tertiaryAppearanceMixin.ts
  src/components/Button/index.tsx
  src/components/Button/stories/Button.stories.tsx
  src/components/Button/stories/ButtonLoader.template.tsx
  src/components/Button/stories/ButtonStyles.template.tsx
  src/components/Button/stories/ButtonWithBadge.template.tsx
  src/components/Button/stories/ButtonWithIcon.template.tsx
  src/components/Button/types.ts
  src/components/MenuButton/__snapshots__/MenuButton.test.tsx.snap
  src/components/MenuButton/index.tsx
  src/components/MenuButton/stories/MenuButton.stories.tsx
  src/components/MultiButton/__snapshots__/MultiButton.test.tsx.snap
  src/components/MultiButton/index.tsx
  src/components/MultiButton/stories/MultiButton.stories.tsx
  src/components/MultiButton/stories/MultiButtonAppearance.template.tsx
  src/components/MultiButton/stories/MultiButtonDisabled.template.tsx
  src/components/MultiButton/stories/MultiButtonIcon.template.tsx
  src/components/PaginationOne/PaginationButton.tsx
  src/components/PaginationOne/index.tsx
Labels: feature

#1377 1361 suggestfield некорретная ширина label при displayinline
  src/components/Field/index.tsx
  src/components/form/DateField/__snapshots__/DateField.test.tsx.snap
Labels: bug

#1378 feat(Flex): добавлена возможность введения необходимых значений свойс…
  src/components/Flex/Flex.styled.tsx
  src/components/Flex/Flex.types.ts
  src/components/Flex/Flex.utils.ts
  src/components/Flex/stories/FlexPlayground.template.tsx
Labels: feature

#1383 docs(Table): #1382 дополнена документация по таблице, указано, что та…
  src/components/Table/stories/TablePlayground.template.tsx
Labels: documentation

#1386 1376 table column header hover cursor
  src/components/Table/HeaderCell.tsx
  src/components/Table/TitleText.tsx
  src/components/Table/style.ts
Labels: bug

#1395 Рефактор deprecated параметров в компонентах
  src/components/AvatarBase/index.tsx
  src/components/Button/dimensionMixin.ts
  src/components/Button/index.tsx
  src/components/Button/types.ts
  src/components/Calendar/interfaces.ts
  src/components/Chips/index.tsx
  src/components/DropDownMenu/index.tsx
  src/components/DropMenu/index.tsx
  src/components/Dropdown/index.tsx
  src/components/DropdownContainer/index.tsx
  src/components/GroupActionsPane/index.tsx
  src/components/Hint/index.tsx
  src/components/Menu/MenuItemWithCheckbox.tsx
  src/components/Menu/index.tsx
  src/components/MenuButton/index.tsx
  src/components/MultiButton/index.tsx
  src/components/OverflowMenu/index.tsx
  src/components/PaginationOne/index.tsx
  src/components/PaginationSimple/index.tsx
  src/components/PositionInPortal.tsx
  src/components/SelectTree/index.tsx
  src/components/TabMenu/index.tsx
  src/components/Table/types.ts
  src/components/Tag/index.tsx
  src/components/TagMenu/index.tsx
  src/components/TextButton/index.tsx
  src/components/TextButtonMenu/index.tsx
  src/components/Toast/ToastProvider.tsx
  src/components/Tooltip/index.tsx
  src/components/TooltipHOC/index.tsx
  src/components/Tree/TreeNode.tsx
  src/components/Typography/typography.ts
  src/components/input/EditMode/index.tsx
  src/components/input/FileInput/index.tsx
  src/components/input/FileUploader/index.tsx
  src/components/input/FileUploader/utils.ts
  src/components/input/InputEx/index.tsx
  src/components/input/Select/index.tsx
  src/components/themes/common/zIndex.ts
Labels: documentation

#1393 1083 рефактор параметров с помощью которых можно задать элемент относительно которого будет позиционироваться портал
  src/components/DropMenu/index.tsx
  src/components/DropdownContainer/index.tsx
  src/components/GlobalSearch/index.tsx
  src/components/form/InputExField/stories/InputExField.stories.tsx
  src/components/form/SelectField/stories/SelectField.stories.tsx
  src/components/form/SuggestField/stories/SuggestField.stories.tsx
  src/components/input/InputEx/SuffixSelect.tsx
  src/components/input/InputEx/index.tsx
  src/components/input/InputEx/stories/InputEx.stories.tsx
  src/components/input/Select/index.tsx
  src/components/input/SuggestInput/index.tsx
  src/components/input/SuggestInput/stories/SuggestInput.stories.tsx
Labels: feature

#1391 feat(MenuButton): удален проп displayAsSquare
  src/components/MenuButton/index.tsx
Labels: feature

#1390 refactor(Table): #1388 обновлен цвет иконок перетаскивания (drag&drop…
  src/components/Table/style.ts
Labels: refactor

#1389 fix(Table): #1387 исправлен баг с морганием ExpandedRow
  src/components/Table/Row/ExpandedRow.tsx
Labels: bug

#1404 1356 feature cardtab
  src/components/TabMenuComponent/containers/HorizontalCardTabMenuContainer.tsx
  src/components/TabMenuComponent/containers/index.ts
  src/components/TabMenuComponent/stories/horizontalCardTabMenuStories/CardTabMenuHorizontal.stories.tsx
  src/components/TabMenuComponent/stories/horizontalCardTabMenuStories/CardTabMenuHorizontalTemplate.tsx
  src/components/TabMenuComponent/tabMenus/CardTabMenuHorizontal.tsx
  src/components/TabMenuComponent/tabMenus/index.ts
  src/components/TabMenuComponent/tabs/CardTab.tsx
  src/components/TabMenuComponent/tabs/index.ts
Labels: feature

#1408 1346 некорректное поведение раскрывающегося меню в таблице
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/MultiButton/__snapshots__/MultiButton.test.tsx.snap
  src/components/Table/OverflowMenu.tsx
  src/components/Table/Row/RowWrapper.tsx
  src/components/Table/index.tsx
Labels: bug

#1410 1394 создать единый интерфейс для всех компонентов с выпадающим меню для унифицирования пропсов
  src/components/AvatarBaseGroup/index.tsx
  src/components/Breadcrumbs/index.tsx
  src/components/DropMenu/index.tsx
  src/components/DropdownContainer/index.tsx
  src/components/GlobalSearch/index.tsx
  src/components/MenuButton/index.tsx
  src/components/MultiButton/index.tsx
  src/components/OverflowMenu/index.tsx
  src/components/PaginationOne/Menu.tsx
  src/components/PaginationOne/index.tsx
  src/components/TabMenu/index.tsx
  src/components/TabMenuComponent/tabMenus/CardTabMenuHorizontal.tsx
  src/components/TabMenuComponent/tabMenus/TabMenuHorizontal.tsx
  src/components/TabMenuComponent/tabMenus/TabMenuVertical.tsx
  src/components/TabMenuComponent/types.ts
  src/components/TagMenu/index.tsx
  src/components/TextButtonMenu/index.tsx
  src/components/input/DateInput/index.tsx
  src/components/input/InputEx/Menu.tsx
  src/components/input/InputEx/SuffixSelect.tsx
  src/components/input/InputEx/index.tsx
  src/components/input/PhoneNumberInput/index.tsx
  src/components/input/Select/index.tsx
  src/components/input/Select/stories/searchSelect/SearchSelectMultipleWithAddOption.template.tsx
  src/components/input/Select/stories/searchSelect/SearchSelectMultipleWithApply.template.tsx
  src/components/input/Select/stories/searchSelect/SearchSelectWithAddButton.template.tsx
  src/components/input/SuggestInput/index.tsx
  src/components/input/TimeInput/index.tsx
Labels: refactor
