Repository AdmiralDS/react-ui, pull requests merged in 2025-03, with the labels that each got.

#1693 1633 feature paginationtwo
  .gitignore
  .vscode/settings.json
  src/components/PaginationTwo/Items.tsx
  src/components/PaginationTwo/index.tsx
  src/components/PaginationTwo/stories/PaginationTwo.stories.tsx
  src/components/PaginationTwo/stories/PaginationTwoMobile.template.tsx
  src/components/PaginationTwo/stories/PaginationTwoPlayground.template.tsx
  src/components/PaginationTwo/stories/PaginationTwoSettings.template.tsx
  src/components/PaginationTwo/stories/PaginationTwoVariants.template.tsx
  src/components/PaginationTwo/utils.ts
Labels: feature

#1694 fix(Select): исправлен размер шрифта сообщения, отображаемого при пустом наборе опций
  src/components/input/Select/index.tsx
Labels: bug

#1695 fix(Select): исправлена внешняя фильтрация в режиме multiple
  src/components/TextButton/commonMixin.ts
  src/components/input/Select/stories/searchSelect/SearchSelectExternalFilter.template.tsx
Labels: bug

#1705 feat(Modal, Drawer): #1672 add propsConfig function for close button
  src/components/Breadcrumbs/BreadCrumb.tsx
  src/components/Drawer/index.tsx
  src/components/Drawer/stories/Drawer.stories.tsx
  src/components/Drawer/stories/DrawerPlayground.template.tsx
  src/components/Modal/index.tsx
  src/components/Modal/stories/ModalTwoButtons.template.tsx
  src/components/PaginationOne/index.tsx
Labels: enhancement

#1710 1698 designreview carousel
  src/components/Carousel/Carousel.test.tsx
  src/components/Carousel/CarouselButton.tsx
  src/components/Carousel/__snapshots__/Carousel.test.tsx.snap
  src/components/Carousel/index.tsx
  src/components/CarouselSlider/CarouselSlider.test.tsx
  src/components/CarouselSlider/CarouselSliderItem.test.tsx
  src/components/CarouselSlider/__snapshots__/CarouselSliderItem.test.tsx.snap
Labels: enhancement

#1712 1697 designreview notification
  src/components/NotificationItem/__snapshots__/NotificationItem.test.tsx.snap
  src/components/NotificationItem/index.tsx
  src/components/NotificationItem/stories/NotificationItem.stories.tsx
  src/components/NotificationItem/stories/NotificationItemBase.template.tsx
  src/components/NotificationItem/stories/NotificationItemStatus.template.tsx
Labels: enhancement

#1723 1669 editmode
  src/components/input/EditMode/index.tsx
  src/components/input/EditMode/stories/EditModePlayground.template.tsx
  src/components/input/EditMode/types.ts
  src/components/input/EditModeArea/index.tsx
  src/components/input/EditModeArea/stories/EditModeAreaPlayground.template.tsx
Labels: enhancement

#1722 feat(Select): #1670 add propsConfig function for clear and open buttons
  src/components/input/Select/index.tsx
  src/components/input/Select/stories/select/SelectSimple.template.tsx
Labels: enhancement

#1738 feat(TextArea): #1729 добавлена опция копирования текста
  src/components/input/EditModeArea/index.tsx
  src/components/input/TextArea/TextArea.test.tsx
  src/components/input/TextArea/index.tsx
  src/components/input/TextArea/stories/TextAreaPlayground.template.tsx
  src/components/themes/common/locales.ts
Labels: feature

#1739 feat(CardTab): #1726 изменен цвет бейджа
  src/components/TabMenuComponent/stories/horizontalCardTabMenuStories/CardTabMenuHorizontalTemplate.tsx
  src/components/TabMenuComponent/stories/horizontalCardTabMenuStories/CardTabMenuHorizontalWithAddButtonTemplate.tsx
  src/components/TabMenuComponent/stories/horizontalCardTabMenuStories/CardTabMenuHorizontalWithoutBorderTemplate.tsx
  src/components/TabMenuComponent/tabElements/TabBadge.tsx
Labels: feature
